GVAR(players) = [
    ["Stonebridge", "Company Commander - Maj.Fisher.M", "UKSF_B_Officer", "MAJOR"],
    ["Stonebridge", "Company Medic - Sgt.Large.S", "UKSF_B_Medic", "SERGEANT"],
    ["Stonebridge", "Company RTO", "UKSF_B_Rifleman", "CORPORAL"],
    ["Stonebridge", "Company JTAC", "UKSF_B_Rifleman", "CORPORAL"],
    ["Guardian 1", "Platoon Commander - Capt.Bridgford.A", "UKSF_B_Officer", "CAPTAIN"],
    ["Guardian 1", "Platoon Sergeant - Sgt.Handisides.M", "UKSF_B_Rifleman", "SERGEANT"],
    ["Guardian 1", "Platoon Medic - Cpl.Darrington.J", "UKSF_B_Medic", "CORPORAL"],
    ["Guardian 1", "Platoon Medic - LCpl.Lars.R", "UKSF_B_Medic", "PRIVATE"],
    ["Guardian 1", "Platoon Medic - Pte.Stanton.M", "UKSF_B_Medic", "PRIVATE"],
    ["Guardian 1", "Platoon Medic - Pte.Tam.P", "UKSF_B_Medic", "PRIVATE"],
    ["Guardian 1", "Platoon RTO", "UKSF_B_Rifleman", "CORPORAL"],
    ["Guardian 1", "Platoon FAC", "UKSF_B_Rifleman", "CORPORAL"],
    ["Guardian 1-1", "Section Leader", "UKSF_B_SectionLeader", "CORPORAL"],
    ["Guardian 1-1", "2iC", "UKSF_B_SectionLeader", "PRIVATE"],
    ["Guardian 1-1", "Rifleman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Guardian 1-1", "Rifleman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Guardian 1-1", "Gunner", "UKSF_B_MachineGunner", "PRIVATE"],
    ["Guardian 1-1", "Marksman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Guardian 1-2", "Section Leader", "UKSF_B_SectionLeader", "CORPORAL"],
    ["Guardian 1-2", "2iC", "UKSF_B_SectionLeader", "PRIVATE"],
    ["Guardian 1-2", "Rifleman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Guardian 1-2", "Rifleman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Guardian 1-2", "Gunner", "UKSF_B_MachineGunner", "PRIVATE"],
    ["Guardian 1-2", "Marksman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Guardian 1-3", "Section Leader", "UKSF_B_SectionLeader", "CORPORAL"],
    ["Guardian 1-3", "2iC", "UKSF_B_SectionLeader", "PRIVATE"],
    ["Guardian 1-3", "Rifleman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Guardian 1-3", "Rifleman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Guardian 1-3", "Gunner", "UKSF_B_MachineGunner", "PRIVATE"],
    ["Guardian 1-3", "Marksman", "UKSF_B_Rifleman", "PRIVATE"],
    ["Ghost", "Commander - Cpl.Blivejazz.M", "UKSF_B_Sniper", "CORPORAL"],
    ["Ghost", "Sniper", "UKSF_B_Sniper", "PRIVATE"],
    ["Ghost", "Spotter", "UKSF_B_Sniper", "PRIVATE"],
    ["Ghost", "JTAC", "UKSF_B_Rifleman", "CORPORAL"],
    ["Ghost", "Medic", "UKSF_B_Medic", "CORPORAL"],
    ["Pegasus 1", "Commander - OCdt.Bishop.S", "UKSF_B_AntiTank", "CORPORAL"],
    ["Pegasus 1", "Driver - LCpl.Redcoat.C", "UKSF_B_AntiTank", "PRIVATE"],
    ["Pegasus 1", "Gunner - Pte.Penn.L", "UKSF_B_AntiTank", "PRIVATE"],
    ["Pegasus 2", "Commander - Pte.Pothoven.B", "UKSF_B_AntiTank", "PRIVATE"],
    ["Pegasus 2", "Driver - Pte.Gustas.J", "UKSF_B_AntiTank", "PRIVATE"],
    ["Pegasus 2", "Gunner - Pte.Brzozowski.T", "UKSF_B_AntiTank", "PRIVATE"],
    ["Pegasus 3", "Commander - Cpl.Alwandy.J", "UKSF_B_AntiTank", "CORPORAL"],
    ["Pegasus 3", "Driver - Pte.Hutton.D", "UKSF_B_AntiTank", "PRIVATE"],
    ["Pegasus 3", "Gunner - Pte.Darczuk.M", "UKSF_B_AntiTank", "PRIVATE"],
    ["JSFAW", "Commander - SqnLdr.Beswick.T", "UKSF_B_Pilot_617", "MAJOR"],
    ["JSFAW", "2iC - FltLt.Johnson.R", "UKSF_B_Pilot_7", "CAPTAIN"],
    ["JSFAW", "656 Sqn. Pilot - FgOff.Kroonen.K", "UKSF_B_Pilot_656", "LIEUTENANT"],
    ["JSFAW", "656 Sqn. Pilot - PltOff.Greaves.A", "UKSF_B_Pilot_656", "LIEUTENANT"],
    ["JSFAW", "7 Sqn. Pilot - ACdt.Conway.M", "UKSF_B_Pilot_7", "PRIVATE"]
];
