name = "UKSF"
prefix = "uksf"
author = "UKSF SR3 Team"
files = [
    "mod.cpp",
    "mod.paa",
    "modLarge.paa",
    "README.md",
    "AUTHORS.txt",
    "LICENSE"
]

modname = "uksf"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

check = [
    "!binarizer_link"
]
releasebuild = [
    "@zip uksf_v{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"

# Binarizer file search compatibility
[scripts.binarizer_link]
steps_windows = [
    "if not exist u\\uksf mkdir u\\uksf",
    "if not exist u\\uksf\\addons mklink /j u\\uksf\\addons addons",
    "if not exist a3 mklink /j a3 include\\a3"
]
steps_linux = [
    # Preparation for Windows Binarizer (run once on Linux for network share compatibility)
    "mkdir -p u/uksf",
    "[ -d u/uksf/addons ] || ln -sr addons u/uksf/",
    "mkdir -p a3",
    "[ -d a3 ] || ln -sr include/a3 a3/"
]
show_output = true
