class GVAR(loadouts) {
    class GVAR(loadout_empty) {
        name = "Empty";
        loadout = "[[],[],[],[],[],[],'','',[],['ItemMap','ItemGPS','','ItemCompass','ItemWatch','']]";
    };
    class GVAR(loadout_pilot617) {
        name = "Pilot: 617 Squadron";
        loadout = "[[],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UKSF_U_PilotGSuit_617',[['ACE_elasticBandage',5],['ACE_EarPlugs',1],['ACE_packingBandage',5],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACRE_PRC152',1],['UK3CB_BAF_9_17Rnd',4,17],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['B_IR_Grenade',2,1],['Chemlight_red',2,1],['ACE_HandFlare_Red',2,1]]],[],['B_Parachute',[]],'H_PilotHelmetFighter_B','',[],['ItemMap','B_UavTerminal','','ItemCompass','ItemWatch','']]";
    };
    class GVAR(loadout_pilot656) {
        name = "Pilot: 656 Squadron";
        loadout = "[['UK3CB_BAF_L22A2','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd',30],[],''],[],[],['UKSF_U_PilotUniform_656',[['ACE_elasticBandage',5],['ACE_packingBandage',5],['ACE_MapTools',1],['ACE_Flashlight_XL50',1]]],['UK3CB_BAF_V_Pilot_A',[['ACE_EarPlugs',1],['ACRE_PRC152',1],['UK3CB_BAF_556_30Rnd',5,30],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['HandGrenade',2,1],['B_IR_Grenade',2,1],['ACE_HandFlare_Red',2,1],['Chemlight_red',2,1]]],[],'UK3CB_BAF_H_PilotHelmetHeli_A','',[],['ItemMap','ItemGPS','','ItemCompass','ItemWatch','ACE_NVG_Pilot']]";
    };
    class GVAR(loadout_pilot7) {
        name = "Pilot: 7 Squadron";
        loadout = "[[],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UKSF_U_PilotCoveralls_7',[['UK3CB_BAF_9_17Rnd',4,17]]],['UKSF_V_Pilot',[['ACE_elasticBandage',5],['ACE_EarPlugs',1],['ACE_packingBandage',5],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACRE_PRC152',1],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['Chemlight_red',2,1],['B_IR_Grenade',2,1],['ACE_HandFlare_Red',2,1]]],[],'UK3CB_BAF_H_PilotHelmetHeli_A','',[],['ItemMap','ItemGPS','','ItemCompass','ItemWatch','ACE_NVG_Pilot']]";
    };
    class GVAR(loadout_sfsgDiver) {
        name = "SFSG: Diver";
        loadout = "[['SSQN_L119A1_CQB','SSQN_FA556212_Suppressor','UK3CB_BAF_LLM_Flashlight_Black','RKSL_optic_LDS',['UK3CB_BAF_556_30Rnd',30],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_B_Wetsuit',[['ACRE_PRC343',1],['ACRE_PRC152',1],['ACE_Flashlight_MX991',1],['ACE_tourniquet',4],['ACE_M26_Clacker',1],['ACE_CableTie',5],['ACE_EarPlugs',1],['ACE_packingBandage',10],['ACE_elasticBandage',10],['ACE_IR_Strobe_Item',1],['UK3CB_BAF_9_17Rnd',2,17],['ACE_Chemlight_UltraHiOrange',2,1],['ACE_Chemlight_IR',2,1]]],['V_RebreatherB',[]],['Black_Carryall',[['DemoCharge_Remote_Mag',1,1],['CUP_HandGrenade_L109A2_HE',1,1],['UK3CB_BAF_SmokeShell',4,1],['UK3CB_BAF_SmokeShellGreen',2,1],['ACE_Chemlight_IR',2,1],['UK3CB_BAF_556_30Rnd',5,30],['UK3CB_BAF_556_30Rnd_T',5,30],['ACE_M84',2,1],['ACE_Chemlight_UltraHiOrange',1,1],['VSM_FAPC_Operator_Multicam',false],['VSM_Multicam_Crye_SS_Camo',false]]],'VSM_OPS_multicam','G_B_Diving',['ACE_Vector','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','CUP_NVG_PVS15_black']]";
    };
    class GVAR(loadout_sfsgGPMG) {
        name = "SFSG: GPMG";
        loadout = "[['UK3CB_BAF_L7A2','','','',['UK3CB_BAF_762_100Rnd_T_EL',100],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['VSM_Multicam_Crye_Camo',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2]]],['VSM_RAV_MG_Multicam',[['ACRE_PRC343',1],['ACRE_PRC152',1],['UK3CB_BAF_9_17Rnd',2,17],['UK3CB_BAF_SmokeShell',3,1],['B_IR_Grenade',1,1],['UK3CB_BAF_762_100Rnd_T_EL',2,100]]],['UK3CB_BAF_B_Kitbag_MTP',[['ACE_EntrenchingTool',1],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['muzzle_snds_L',1],['CUP_NVG_PVS15_black',1],['UK3CB_BAF_762_100Rnd_T_EL',1,100]]],'VSM_OPS_multicam','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_sfsgGrenadier) {
        name = "SFSG: Grenadier";
        loadout = "[['UK3CB_BAF_L119A1_UKUGL','','UK3CB_BAF_LLM_IR_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],['UK3CB_BAF_1Rnd_Smoke_Grenade_shell',1],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['VSM_Multicam_Crye_Camo',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2]]],['VSM_RAV_MG_Multicam',[['ACRE_PRC343',1],['ACRE_PRC152',1],['UK3CB_BAF_556_30Rnd_T',10,30],['UK3CB_BAF_9_17Rnd',2,17],['CUP_HandGrenade_L109A1_HE',5,1],['UK3CB_BAF_SmokeShell',2,1],['B_IR_Grenade',1,1]]],['UK3CB_BAF_B_Kitbag_MTP',[['ACE_EntrenchingTool',1],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['SSQN_FA556212_Suppressor',1],['muzzle_snds_L',1],['CUP_NVG_PVS15_black',1],['UK3CB_BAF_1Rnd_HE_Grenade_Shell',20,1],['UK3CB_BAF_1Rnd_Smoke_Grenade_shell',10,1],['UK3CB_BAF_1Rnd_SmokeRed_Grenade_shell',5,1],['UK3CB_BAF_1Rnd_SmokeBlue_Grenade_shell',5,1]]],'VSM_OPS_multicam','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_sfsgIRS) {
        name = "SFSG: IRS";
        loadout = "[['UK3CB_BAF_L85A3_Grippod','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd',30],[],''],[],['UK3CB_BAF_L131A1','','UK3CB_BAF_Flashlight_L131A1','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_B_GhillieSuit',[['ACE_CableTie',2],['ACE_EarPlugs',1],['ACE_DefusalKit',1],['ACE_EntrenchingTool',1],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACE_microDAGR',1],['ACE_packingBandage',9]]],['UK3CB_BAF_V_Osprey_Holster',[['UK3CB_BAF_556_30Rnd',5,30],['B_IR_Grenade',2,1]]],['UK3CB_BAF_B_Kitbag_MTP',[['UK3CB_BAF_SmokeShellBlue',1,1],['UK3CB_BAF_SmokeShellGreen',1,1],['UK3CB_BAF_SmokeShellOrange',1,1],['UK3CB_BAF_SmokeShellPurple',1,1],['UK3CB_BAF_SmokeShellRed',1,1],['UK3CB_BAF_SmokeShellYellow',1,1],['UK3CB_BAF_SmokeShell',2,1],['ACE_M84',2,1],['ACE_Chemlight_IR',3,1],['APERSTripMine_Wire_Mag',1,1],['UK3CB_BAF_9_17Rnd',1,17]]],'','',[],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','UK3CB_BAF_HMNVS']]";
    };
    class GVAR(loadout_sfsgLMG) {
        name = "SFSG: LMG";
        loadout = "[['UK3CB_BAF_L110A3','','UK3CB_BAF_LLM_IR_Black','SSQN_AR_EOTech553',['UK3CB_BAF_556_200Rnd_T',200],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['VSM_Multicam_Crye_Camo',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2]]],['VSM_RAV_MG_Multicam',[['ACRE_PRC343',1],['ACRE_PRC152',1],['UK3CB_BAF_9_17Rnd',2,17],['UK3CB_BAF_SmokeShell',3,1],['B_IR_Grenade',1,1],['UK3CB_BAF_556_200Rnd_T',2,200]]],['UK3CB_BAF_B_Kitbag_MTP',[['ACE_EntrenchingTool',1],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['muzzle_snds_L',1],['CUP_NVG_PVS15_black',1],['UK3CB_BAF_556_200Rnd_T',1,200]]],'VSM_OPS_multicam','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_sfsgMarksman) {
        name = "SFSG: Marksman";
        loadout = "[['UK3CB_BAF_L129A1','','UK3CB_BAF_LLM_IR_Black','UK3CB_BAF_TA648_308',['UK3CB_BAF_762_L42A1_20Rnd',20],[],'UK3CB_underbarrel_acc_fgrip_bipod'],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['VSM_Multicam_Crye_Camo',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2]]],['VSM_RAV_MG_Multicam',[['ACRE_PRC343',1],['ACRE_PRC152',1],['UK3CB_BAF_9_17Rnd',2,17],['UK3CB_BAF_SmokeShell',3,1],['B_IR_Grenade',1,1],['UK3CB_BAF_762_L42A1_20Rnd',8,20]]],['UK3CB_BAF_B_Kitbag_MTP',[['ACE_EntrenchingTool',1],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['muzzle_snds_L',1],['CUP_NVG_PVS15_black',1],['UK3CB_BAF_Silencer_L115A3',1]]],'VSM_OPS_multicam','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_sfsgMedic) {
        name = "SFSG: Medic";
        loadout = "[['SSQN_L119A1_SFW_v2','SSQN_FA556212_Suppressor','UK3CB_BAF_LLM_IR_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['VSM_Multicam_Crye_SS_Camo',[['ACE_EarPlugs',2],['ACE_tourniquet',4],['ACE_CableTie',2],['CUP_NVG_PVS15_black',1],['ACRE_PRC343',1],['SmokeShellBlue',2,1],['SmokeShellRed',1,1]]],['VSM_RAV_MG_Multicam',[['ACE_bloodIV',5],['ACE_bloodIV_250',5],['ACE_bloodIV_500',5],['ACE_EntrenchingTool',1],['ACRE_PRC152',1],['ACE_splint',8],['SmokeShell',3,1],['SmokeShellGreen',1,1],['ACE_Chemlight_IR',2,1],['UK3CB_BAF_556_30Rnd_T',11,30]]],['UK3CB_BAF_B_Kitbag_MTP',[['ACE_elasticBandage',70],['ACE_personalAidKit',1],['ACE_packingBandage',70],['ACE_epinephrine',25],['ACE_adenosine',5],['ACE_bloodIV',3],['ACE_bloodIV_500',3],['ACE_tourniquet',4],['ACE_surgicalKit',1],['ACE_morphine',25],['ACE_bloodIV_250',3]]],'VSM_OPS_2_multicam','',['ACE_Vector','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_sfsgRifleman) {
        name = "SFSG: Rifleman";
        loadout = "[['SSQN_L119A1_SFW','','UK3CB_BAF_LLM_IR_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['VSM_Multicam_Crye_Camo',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2]]],['VSM_RAV_MG_Multicam',[['UK3CB_BAF_556_30Rnd_T',11,30],['UK3CB_BAF_9_17Rnd',2,17],['CUP_HandGrenade_L109A1_HE',2,1],['UK3CB_BAF_SmokeShell',2,1],['B_IR_Grenade',1,1]]],['UK3CB_BAF_B_Kitbag_MTP',[['ACE_EntrenchingTool',1],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['ACRE_PRC152',1],['ACRE_PRC343',1],['SSQN_FA556212_Suppressor',1],['muzzle_snds_L',1],['CUP_NVG_PVS15_black',1]]],'VSM_OPS_multicam','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
};
// copyToClipboard str (getUnitLoadout player)
