class GVAR(loadouts) {
    class GVAR(loadout_1paraBreacher) {
        name = "1 Para: Breacher";
        loadout = "[['UK3CB_BAF_L85A2_RIS','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],[],''],[],[],['UK3CB_BAF_U_CombatUniform_MTP_1Para',[['ACE_CableTie',2],['ACE_Flashlight_XL50',1],['ACE_EarPlugs',1],['ACE_MapTools',1],['ACRE_PRC152',1]]],['UK3CB_BAF_V_Osprey_Rifleman_E',[['B_IR_Grenade',2,1],['UK3CB_BAF_SmokeShell',3,1],['HandGrenade',4,1],['UK3CB_BAF_556_30Rnd_T',4,30],['UK3CB_BAF_12G_Pellets',3,8],['UK3CB_BAF_SmokeShellBlue',1,1]]],['UK3CB_BAF_B_Bergen_MTP_PointMan_L_A',[['ACE_packingBandage',10],['UK3CB_BAF_HMNVS',1],['UK3CB_BAF_556_30Rnd_T',5,30],['UK3CB_BAF_12G_Pellets',3,8]]],'UK3CB_BAF_H_Mk7_Camo_B','',[],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_1paraGrenadier) {
        name = "1 Para: Grenadier";
        loadout = "[['UK3CB_BAF_L85A2_RIS','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],[],''],[],[],['UK3CB_BAF_U_CombatUniform_MTP_1Para',[['ACE_CableTie',2],['ACE_Flashlight_XL50',1],['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_packingBandage',10],['ACRE_PRC152',1]]],['UK3CB_BAF_V_Osprey_Grenadier_A',[['B_IR_Grenade',1,1],['UK3CB_BAF_SmokeShell',3,1],['UK3CB_BAF_SmokeShellGreen',1,1],['UK3CB_BAF_SmokeShellBlue',2,1],['HandGrenade',3,1],['UK3CB_BAF_556_30Rnd_T',4,30]]],['UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C',[['UK3CB_BAF_HMNVS',1],['ACE_EntrenchingTool',1],['UK3CB_BAF_556_30Rnd_T',4,30],['HandGrenade',3,1]]],'UK3CB_BAF_H_Mk7_Camo_B','',[],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ItemWatch','']]";
    };
    class GVAR(loadout_1paraRifleman) {
        name = "1 Para: Rifleman";
        loadout = "[['UK3CB_BAF_L85A2_RIS','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],[],''],[],[],['UK3CB_BAF_U_CombatUniform_MTP_1Para',[['ACE_CableTie',2],['ACE_Flashlight_XL50',1],['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_packingBandage',10],['ACRE_PRC152',1]]],['UK3CB_BAF_V_Osprey_Rifleman_C',[['B_IR_Grenade',1,1],['UK3CB_BAF_SmokeShell',3,1],['UK3CB_BAF_SmokeShellGreen',1,1],['UK3CB_BAF_SmokeShellBlue',2,1],['HandGrenade',3,1],['UK3CB_BAF_556_30Rnd_T',4,30]]],['UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C',[['UK3CB_BAF_HMNVS',1],['ACE_EntrenchingTool',1],['UK3CB_BAF_556_30Rnd_T',4,30]]],'UK3CB_BAF_H_Mk7_Camo_B','',[],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ItemWatch','']]";
    };
    class GVAR(loadout_1paraSectionLeader) {
        name = "1 Para: Section Leader";
        loadout = "[['UK3CB_BAF_L85A2_UGL','','UK3CB_BAF_LLM_IR_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],['1Rnd_HE_Grenade_shell',1],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UK3CB_BAF_U_CombatUniform_MTP_1Para_ShortSleeve',[['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_MapTools',1],['UK3CB_BAF_HMNVS',1],['ACE_EarPlugs',1],['ACRE_PRC152',1]]],['UK3CB_BAF_V_Osprey_Grenadier_A',[['ACE_IR_Strobe_Item',1],['UK3CB_BAF_556_30Rnd_T',4,30],['1Rnd_HE_Grenade_shell',2,1],['ACE_HuntIR_M203',3,1],['B_IR_Grenade',2,1],['UK3CB_BAF_SmokeShellBlue',1,1],['UK3CB_BAF_SmokeShellGreen',1,1],['HandGrenade',2,1],['UK3CB_BAF_SmokeShell',5,1],['UK3CB_BAF_9_17Rnd',1,17]]],['UK3CB_BAF_B_Bergen_MTP_SL_L_A',[['ACE_EntrenchingTool',1],['ACE_HuntIR_monitor',1],['ACE_packingBandage',10],['UK3CB_BAF_556_30Rnd_T',5,30],['1Rnd_HE_Grenade_shell',7,1],['ACRE_PRC152',1]]],'UK3CB_BAF_H_Mk7_Camo_A','',[],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_1paraLMG) {
        name = "1 Para: LMG";
        loadout = "[['UK3CB_BAF_L110A3','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_100Rnd',100],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UK3CB_BAF_U_CombatUniform_MTP_1Para',[['ACE_EarPlugs',1],['ACE_CableTie',2],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_packingBandage',10],['ACRE_PRC152',1]]],['UK3CB_BAF_V_Osprey_MG_B',[['B_IR_Grenade',1,1],['HandGrenade',2,1],['UK3CB_BAF_SmokeShell',3,1],['UK3CB_BAF_556_100Rnd',1,100]]],['UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D',[['ACE_CableTie',2],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_MapTools',1],['UK3CB_BAF_HMNVS',1],['ACE_packingBandage',12],['ACE_EntrenchingTool',1],['UK3CB_BAF_556_100Rnd',1,100]]],'UK3CB_BAF_H_Mk7_Net_B','',[],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ItemWatch','']]";
    };
    class GVAR(loadout_1paraAT) {
        name = "1 Para: AT";
        loadout = "[['UK3CB_BAF_L85A2_RIS','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],[],''],['UK3CB_BAF_AT4_CS_AT_Launcher','','','',[],[],''],[],['UK3CB_BAF_U_CombatUniform_MTP_1Para',[['ACE_CableTie',2],['ACE_Flashlight_XL50',1],['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_packingBandage',10],['ACRE_PRC152',1]]],['UK3CB_BAF_V_Osprey_Rifleman_C',[['B_IR_Grenade',1,1],['UK3CB_BAF_SmokeShell',3,1],['UK3CB_BAF_SmokeShellGreen',1,1],['UK3CB_BAF_SmokeShellBlue',2,1],['HandGrenade',3,1],['UK3CB_BAF_556_30Rnd_T',4,30]]],['UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C',[['UK3CB_BAF_HMNVS',1],['ACE_EntrenchingTool',1],['UK3CB_BAF_556_30Rnd_T',4,30]]],'UK3CB_BAF_H_Mk7_Camo_B','',[],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ItemWatch','']]";
    };
    class GVAR(loadout_1paraAmmoBearer) {
        name = "1 Para: Ammo Bearer";
        loadout = "[['UK3CB_BAF_L85A2_RIS','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd_T',30],[],''],[],[],['UK3CB_BAF_U_CombatUniform_MTP_1Para',[['ACE_CableTie',2],['ACE_Flashlight_XL50',1],['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_packingBandage',10],['ACRE_PRC152',1]]],['UK3CB_BAF_V_Osprey_Rifleman_C',[['B_IR_Grenade',1,1],['UK3CB_BAF_SmokeShell',3,1],['UK3CB_BAF_SmokeShellGreen',1,1],['UK3CB_BAF_SmokeShellBlue',2,1],['HandGrenade',3,1],['UK3CB_BAF_556_30Rnd_T',4,30]]],['UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C',[['UK3CB_BAF_HMNVS',1],['ACE_EntrenchingTool',1],['UK3CB_BAF_556_30Rnd_T',4,30],['UK3CB_BAF_556_100Rnd_T',3,100]]],'UK3CB_BAF_H_Mk7_Camo_B','',[],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ItemWatch','']]";
    };
    class GVAR(loadout_1paraMedic) {
        name = "1 Para: Medic";
        loadout = "[['UK3CB_BAF_L85A2_RIS_AFG','','acc_pointer_IR','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd',30],[],''],[],[],['UK3CB_BAF_U_CombatUniform_MTP_CSMR',[['ACE_EarPlugs',3],['ACRE_PRC152_ID_3',1],['ACRE_PRC152_ID_4',1]]],['UK3CB_BAF_V_Osprey_Medic_B',[['ACE_EarPlugs',1],['ACE_CableTie',2],['ACE_IR_Strobe_Item',1],['ACE_EntrenchingTool',1],['ACE_Flashlight_XL50',1],['UK3CB_BAF_HMNVS',1],['UK3CB_BAF_556_30Rnd',4,30],['UK3CB_BAF_556_30Rnd_T',5,30],['UK3CB_BAF_SmokeShellYellow',3,1],['UK3CB_BAF_SmokeShellGreen',3,1]]],['UK3CB_BAF_B_Bergen_MTP_Medic_L_A',[['ACE_elasticBandage',70],['ACE_packingBandage',70],['ACE_personalAidKit',1],['ACE_morphine',25],['ACE_bloodIV',5],['ACE_bloodIV_250',5],['ACE_epinephrine',25],['ACE_surgicalKit',1],['ACE_tourniquet',5],['UK3CB_BAF_H_Beret_RAMC',1]]],'UK3CB_BAF_H_Mk7_Net_D','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_1paraIRS) {
        name = "1 Para: IRS";
        loadout = "[['UK3CB_BAF_L85A2_RIS','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd',30],[],''],[],['UK3CB_BAF_L131A1','','UK3CB_BAF_Flashlight_L131A1','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_B_GhillieSuit',[['ACE_CableTie',2],['ACE_EarPlugs',1],['ACE_DefusalKit',1],['ACE_EntrenchingTool',1],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACE_microDAGR',1],['ACE_packingBandage',9]]],['UK3CB_BAF_V_Osprey_Holster',[['UK3CB_BAF_556_30Rnd',5,30],['B_IR_Grenade',2,1]]],['UK3CB_BAF_B_Kitbag_MTP',[['UK3CB_BAF_SmokeShellBlue',1,1],['UK3CB_BAF_SmokeShellGreen',1,1],['UK3CB_BAF_SmokeShellOrange',1,1],['UK3CB_BAF_SmokeShellPurple',1,1],['UK3CB_BAF_SmokeShellRed',1,1],['UK3CB_BAF_SmokeShellYellow',1,1],['UK3CB_BAF_SmokeShell',2,1],['ACE_M84',2,1],['ACE_Chemlight_IR',3,1],['APERSTripMine_Wire_Mag',1,1],['UK3CB_BAF_9_17Rnd',1,17]]],'','',[],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ACE_Altimeter','UK3CB_BAF_HMNVS']]";
    };
    class GVAR(loadout_1paraSpotter) {
        name = "1 Para: Spotter";
        loadout = "[['UK3CB_BAF_L129A1_Grippod','UK3CB_BAF_Silencer_L115A3','UK3CB_BAF_LLM_IR_Black','UK3CB_BAF_TA31F',['UK3CB_BAF_762_L42A1_20Rnd_T',20],[],''],[],[],['U_B_FullGhillie_lsh',[]],['UK3CB_BAF_V_PLCE_Webbing_Plate_MTP',[['UK3CB_BAF_762_L42A1_20Rnd_T',9,20]]],['UK3CB_BAF_B_Kitbag_MTP',[['ACE_EarPlugs',1],['ACE_Flashlight_MX991',1],['ACE_MapTools',1],['ACE_microDAGR',1],['ACE_packingBandage',7],['optic_LRPS',1],['UK3CB_BAF_H_Beret_PR',1],['ACRE_PRC152',1],['ACRE_PRC152',1],['ACE_Sandbag_empty',2],['ACE_Tripod',1],['ACE_tourniquet',2],['UK3CB_BAF_SmokeShell',4,1],[['ACE_Vector','','','',[],[],''],1],['UK3CB_BAF_U_CombatUniform_MTP_1Para',false]]],'UK3CB_BAF_H_Boonie_MTP','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_Pathfinder) {
        name = "Pathfinder";
        loadout = "[['UK3CB_BAF_L119A1_UKUGL','UK3CB_BAF_Silencer_L85','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_TA31F',['UK3CB_BAF_556_30Rnd',30],['UK3CB_BAF_1Rnd_HE_Grenade_Shell',1],''],[],['UK3CB_BAF_L131A1','muzzle_snds_L','UK3CB_BAF_Flashlight_L131A1','',['UK3CB_BAF_9_17Rnd',17],[],''],['UK3CB_BAF_U_CombatUniform_MTP_Path_ShortSleeve',[['ACE_CableTie',2],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACE_microDAGR',1],['ACE_packingBandage',10],['UK3CB_BAF_HMNVS',1]]],['V_PlateCarrierL_CTRG',[['ACE_HuntIR_M203',2,1],['UK3CB_BAF_556_30Rnd_T',4,30],['UK3CB_BAF_556_30Rnd',2,30],['UK3CB_BAF_1Rnd_HE_Grenade_Shell',1,1]]],['UK3CB_BAF_B_Kitbag_MTP',[['ACE_EarPlugs',1],['ACE_CableTie',2],['ACE_HuntIR_monitor',1],['ACRE_PRC152',1],['ACRE_PRC152',1],['UK3CB_BAF_9_17Rnd',1,17],['UK3CB_BAF_UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_UK3CB_BAF_SmokeShell',3,1],['B_IR_Grenade',2,1],['HandGrenade',3,1],['ACE_M84',3,1],['UK3CB_BAF_556_30Rnd_T',4,30],['UK3CB_BAF_1Rnd_HE_Grenade_Shell',6,1]]],'UK3CB_BAF_H_Mk7_Net_B','',['ACE_Vector','','','',[],[],''],['ItemMap','ItemGPS','ItemRadioAcreFlagged','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_pilot617) {
        name = "Pilot: 617 Squadron";
        loadout = "[[],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UKSF_U_PilotGSuit_617',[['ACE_fieldDressing',3],['ACE_elasticBandage',3],['ACE_bloodIV_250',2],['ACE_EarPlugs',1],['ACE_epinephrine',2],['ACE_morphine',2],['ACE_packingBandage',2],['ACE_personalAidKit',1],['ACE_surgicalKit',1],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['UK3CB_BAF_9_17Rnd',6,17],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['B_IR_Grenade',2,1],['Chemlight_red',2,1],['ACE_HandFlare_Red',2,1]]],[],['B_Parachute',[['ACRE_PRC117F',1],['ACRE_PRC117F',1]]],'H_PilotHelmetFighter_B','',[],['ItemMap','B_UavTerminal','ItemRadioAcreFlagged','ItemCompass','ItemWatch','']]";
    };
    class GVAR(loadout_pilot656) {
        name = "Pilot: 656 Squadron";
        loadout = "[['UK3CB_BAF_L22A2','','','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd',30],[],''],[],[],['UKSF_U_PilotUniform_656',[]],['UKSF_V_Pilot',[['ACE_fieldDressing',3],['ACE_elasticBandage',3],['ACE_bloodIV_250',2],['ACE_EarPlugs',1],['ACE_epinephrine',2],['ACE_morphine',2],['ACE_packingBandage',2],['ACE_personalAidKit',1],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['UK3CB_BAF_556_30Rnd',5,30],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['CUP_HandGrenade_M67',2,1],['B_IR_Grenade',2,1],['ACE_HandFlare_Red',2,1],['Chemlight_red',2,1]]],['B_Parachute',[['ACRE_PRC117F',1],['ACRE_PRC117F',1]]],'UK3CB_BAF_H_PilotHelmetHeli_A','',[],['ItemMap','B_UavTerminal','ItemRadioAcreFlagged','ItemCompass','ItemWatch','ACE_NVG_Pilot']]";
    };
    class GVAR(loadout_pilot7) {
        name = "Pilot: 7 Squadron";
        loadout = "[[],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UKSF_U_PilotCoveralls_7',[['UK3CB_BAF_9_17Rnd',4,17]]],['UKSF_V_Pilot',[['ACE_fieldDressing',3],['ACE_elasticBandage',3],['ACE_bloodIV_250',2],['ACE_EarPlugs',1],['ACE_epinephrine',2],['ACE_morphine',2],['ACE_packingBandage',2],['ACE_personalAidKit',1],['ACE_surgicalKit',1],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['Chemlight_red',2,1],['B_IR_Grenade',2,1],['ACE_HandFlare_Red',2,1]]],['B_Parachute',[['ACRE_PRC117F',1],['ACRE_PRC117F',1]]],'UK3CB_BAF_H_PilotHelmetHeli_A','',[],['ItemMap','B_UavTerminal','ItemRadioAcreFlagged','ItemCompass','ItemWatch','ACE_NVG_Pilot']]";
    };
};
// copyToClipboard str (getUnitLoadout player)
