class GVAR(loadouts) {
    class GVAR(loadout_empty) {
        name = "Empty";
        loadout = "[[],[],[],[],[],[],'','',[],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_pilotRotary) {
        name = "Pilot: Rotary Transport";
        loadout = "[[],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UK3CB_BAF_U_HeliPilotCoveralls_RAF',[['UK3CB_BAF_9_17Rnd',4,17]]],['UKSF_V_Pilot',[['ACE_elasticBandage',5],['ACE_EarPlugs',1],['ACE_packingBandage',5],['ACE_painkillers',1,10],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACRE_PRC152',1],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['Chemlight_red',2,1],['B_IR_Grenade',2,1],['ACE_HandFlare_Red',2,1]]],[],'UK3CB_BAF_H_PilotHelmetHeli_A','',[],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','ACE_NVG_Pilot']]";
    };
    class GVAR(loadout_pilotRotaryNaval) {
        name = "Pilot: Rotary Transport (Naval)";
        loadout = "[[],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UK3CB_BAF_U_HeliPilotCoveralls_RN',[['UK3CB_BAF_9_17Rnd',4,17]]],['Aircrew_vest_2_NH',[['ACE_elasticBandage',5],['ACE_EarPlugs',1],['ACE_packingBandage',5],['ACE_painkillers',1,10],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACRE_PRC152',1],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['Chemlight_red',2,1],['B_IR_Grenade',2,1],['ACE_HandFlare_Red',2,1]]],[],'UK3CB_BAF_H_PilotHelmetHeli_A','',[],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','ACE_NVG_Pilot']]";
    };
    class GVAR(loadout_pilotRotaryCas) {
        name = "Pilot: Rotary CAS";
        loadout = "[['UK3CB_BAF_L22A2','','UK3CB_BAF_LLM_Flashlight_Black','UK3CB_BAF_SpecterLDS_Dot_3D',['UK3CB_BAF_556_30Rnd',30],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UKSF_U_PilotUniform_656',[['ACE_elasticBandage',15],['ACE_packingBandage',15],['ACE_EarPlugs',1],['ACE_tourniquet',2],['ACE_microDAGR',1],['ACE_EntrenchingTool',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['UK3CB_BAF_9_17Rnd',4,17],['B_IR_Grenade',1,1]]],['UK3CB_BAF_V_Pilot_A',[['ACRE_PRC152',1],['ACE_painkillers',1,10],['UK3CB_BAF_556_30Rnd',5,30],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['B_IR_Grenade',3,1],['ACE_M14',2,1],['ACE_HandFlare_Red',1,1],['ACE_HandFlare_Green',1,1],['UK3CB_BAF_SmokeShell',2,1]]],[],'UK3CB_BAF_H_PilotHelmetHeli_A','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','ACE_NVG_Pilot']]";
    };
    class GVAR(loadout_pilotFastAir) {
        name = "Pilot: Fast Air";
        loadout = "[[],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['UKSF_U_PilotGSuit_617',[['ACE_elasticBandage',5],['ACE_EarPlugs',1],['ACE_packingBandage',5],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACRE_PRC152',1],['ACE_painkillers',1,10],['UK3CB_BAF_9_17Rnd',4,17],['UK3CB_BAF_SmokeShellBlue',2,1],['UK3CB_BAF_SmokeShellOrange',2,1],['UK3CB_BAF_SmokeShellRed',2,1],['B_IR_Grenade',2,1],['Chemlight_red',2,1],['ACE_HandFlare_Red',2,1]]],[],[],'H_PilotHelmetFighter_B','',[],['ItemMap','B_UavTerminal','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_pilotMultiEngine) {
        name = "Pilot: Multi-Engine";
        loadout = "[[],[],[],['UK3CB_BAF_U_HeliPilotCoveralls_RAF',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACRE_PRC152',1],['ACE_elasticBandage',4],['ACE_packingBandage',4],['ACE_painkillers',1,10],['UK3CB_BAF_SmokeShellGreen',1,1],['UK3CB_BAF_SmokeShell',1,1]]],[],[],'UK3CB_BAF_H_PilotHelmetHeli_A','',[],['ItemMap','B_UavTerminal','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_groundRifleman) {
        name = "Ground: Rifleman";
        loadout = "[['arifle_L119A2_S_G_F','CUP_muzzle_snds_M16','UK3CB_BAF_LLM_Flashlight_Far_Black','CUP_optic_Elcan_SpecterDR_RMR_black_PIP',['UK3CB_BAF_556_30Rnd',30],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_mas_ukl_B_CombatUniform_mtp',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2],['ACE_tourniquet',4],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_IR_Strobe_Item',1],['ACE_splint',2],['ACRE_PRC152',1],['ACRE_PRC343',1]]],['V_mas_ukl_PlateCarrierRF_rgr',[['UK3CB_BAF_9_17Rnd',2,17],['CUP_HandGrenade_L109A1_HE',2,1],['UK3CB_BAF_SmokeShell',2,1],['UK3CB_BAF_556_30Rnd_T',9,30],['ACE_M84',2,1]]],['B_Kitbag_mcamo',[['NVGoggles_mas_ukl_hv18',1],['ACE_EntrenchingTool',1],['ACE_bloodIV_500',1]]],'H_mas_ukl_opscorn','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_groundUgl) {
        name = "Ground: UGL";
        loadout = "[[['arifle_mas_ukl_SPAR_01_GL_blk_F','CUP_muzzle_snds_M16','CUP_acc_ANPEQ_15_Flashlight_Black_L','CUP_optic_Elcan_SpecterDR_RMR_black',['UK3CB_BAF_556_30Rnd',30],['1Rnd_HE_Grenade_shell',1],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_mas_ukl_B_CombatUniform_multi',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['ACRE_PRC152',1],['ACRE_PRC343',1],['ACE_IR_Strobe_Item',1],['ACE_splint',2]]],['V_mas_ukl_PlateCarrier1_rgr',[['UK3CB_BAF_9_17Rnd',2,17],['CUP_HandGrenade_L109A1_HE',5,1],['UK3CB_BAF_SmokeShell',2,1],['UK3CB_BAF_556_30Rnd_T',4,30],['ACE_M84',2,1],['UK3CB_BAF_556_30Rnd',2,30]]],['B_Kitbag_mcamo',[['ACE_EntrenchingTool',1],['ACE_bloodIV_500',1],['NVGoggles_mas_ukl_hv18',1],['1Rnd_HE_Grenade_shell',7,1]]],'H_mas_ukl_opscorn','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']],[['ace_earplugs',true]]]";
    };
    class GVAR(loadout_groundLmg) {
        name = "Ground: LMG";
        loadout = "[[['UK3CB_BAF_L110A3','UK3CB_BAF_Silencer_L110','CUP_acc_ANPEQ_15_Flashlight_Black_L','CUP_optic_HoloBlack',['UK3CB_BAF_556_200Rnd_T',200],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_mas_ukl_B_CombatUniform_S_multi',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['ACRE_PRC152',1],['ACRE_PRC343',1],['ACE_splint',2],['ACE_IR_Strobe_Item',1]]],['V_mas_ukl_PlateCarrierAR_civ',[['UK3CB_BAF_556_200Rnd_T',3,200],['CUP_HandGrenade_L109A2_HE',2,1]]],['B_Kitbag_mcamo',[['ACE_EntrenchingTool',1],['NVGoggles_mas_ukl_hv18',1],['UK3CB_BAF_556_200Rnd_T',2,200],['ACE_M84',2,1],['UK3CB_BAF_9_17Rnd',2,17],['UK3CB_BAF_SmokeShell',3,1]]],'H_mas_ukl_opscorn','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']],[['ace_earplugs',true]]]";
    };
    class GVAR(loadout_groundGpmg) {
        name = "Ground: GPMG";
        loadout = "[[['UK3CB_BAF_L7A2','','','',['UK3CB_BAF_762_200Rnd_T_EL',200],[],''],['UK3CB_BAF_Tripod','','','',[],[],''],['UK3CB_BAF_L131A1','','UK3CB_BAF_Flashlight_L131A1','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_mas_ukl_B_CombatUniform_S_multi',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['ACRE_PRC152',1],['ACRE_PRC343',1],['ACE_IR_Strobe_Item',1],['ACE_splint',2]]],['V_mas_ukl_PlateCarrierAR_tan',[['UK3CB_BAF_9_17Rnd',2,17],['UK3CB_BAF_762_200Rnd_T_EL',2,200],['CUP_HandGrenade_L109A2_HE',1,1],['UK3CB_BAF_SmokeShell',2,1]]],['B_mas_ukl_Kitbag_m',[['ACE_EntrenchingTool',1],['NVGoggles_mas_ukl_hv18',1],['ACE_bloodIV_500',1],['UK3CB_BAF_762_200Rnd_T_EL',3,200],['CUP_HandGrenade_L109A2_HE',1,1],['UK3CB_BAF_SmokeShell',1,1]]],'H_mas_ukl_opscorn','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']],[['ace_earplugs',true]]]";
    };
    class GVAR(loadout_groundMarksman) {
        name = "Ground: Marksman";
        loadout = "[['UK3CB_BAF_L129A1_FGrip_Bipod','UK3CB_BAF_Silencer_L115A3','CUP_acc_ANPEQ_15_Flashlight_Black_L','UK3CB_BAF_TA648_308',['UK3CB_BAF_762_L42A1_20Rnd',20],[],'UK3CB_underbarrel_acc_fgrip_bipod'],[],['UK3CB_BAF_L131A1','','UK3CB_BAF_Flashlight_L131A1','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_mas_ukl_B_CombatUniform_multi',[['ACE_EarPlugs',1],['ACE_MapTools',1],['ACE_Flashlight_XL50',1],['ACE_microDAGR',1],['ACE_CableTie',2],['ACE_elasticBandage',10],['ACE_packingBandage',10],['ACE_tourniquet',4],['ACE_IR_Strobe_Item',1],['ACE_splint',2],['ACRE_PRC152',1],['ACRE_PRC343',1]]],['V_mas_ukl_PlateCarrierRF_rgr',[['UK3CB_BAF_9_17Rnd',2,17],['UK3CB_BAF_SmokeShell',3,1],['UK3CB_BAF_762_L42A1_20Rnd',4,20],['UK3CB_BAF_762_L42A1_20Rnd_T',3,20]]],['B_Kitbag_mcamo',[['muzzle_snds_L',1],['ACE_EntrenchingTool',1],['NVGoggles_mas_ukl_hv18',1],['ACE_bloodIV_500',1],['UK3CB_BAF_762_L42A1_20Rnd_T',1,20]]],'H_mas_ukl_opscorn','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']]";
    };
    class GVAR(loadout_groundMedic) {
        name = "Ground: Medic";
        loadout = "[[['arifle_L119A2_S_F_NC','CUP_muzzle_snds_M16','CUP_acc_ANPEQ_15_Flashlight_Black_L','CUP_optic_Elcan_SpecterDR_RMR_black',['UK3CB_BAF_556_30Rnd',30],[],''],[],['UK3CB_BAF_L131A1','','','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_mas_ukl_B_CombatUniform_mtp',[['ACE_EarPlugs',1],['ACE_tourniquet',4],['ACE_CableTie',2],['ACE_splint',4],['ACE_bloodIV_250',2],['ACE_adenosine',1],['ACRE_PRC343',1],['ACRE_PRC152',1],['SmokeShellBlue',2,1],['SmokeShellRed',1,1],['ACE_painkillers',3,10]]],['V_mas_ukl_PlateCarrierLR_tan',[['ACE_bloodIV',5],['ACE_splint',4],['ACE_bloodIV_250',5],['ACE_adenosine',4],['SmokeShell',3,1],['UK3CB_BAF_556_30Rnd',5,30],['UK3CB_BAF_9_17Rnd',1,17]]],['CUP_B_Motherlode_MTP',[['ACE_elasticBandage',70],['ACE_personalAidKit',1],['ACE_packingBandage',70],['ACE_epinephrine',25],['ACE_bloodIV',3],['ACE_bloodIV_500',8],['ACE_tourniquet',4],['ACE_surgicalKit',1],['ACE_morphine',25],['ACE_bloodIV_250',1],['ACE_EntrenchingTool',1],['ACE_IR_Strobe_Item',1],['ACRE_PRC117F',1],['NVGoggles_mas_ukl_hv18',1]]],'H_mas_ukl_opscorn','',['ACE_Vector','','','',[],[],''],['ItemMap','ItemAndroid','','ItemCompass','ACE_Altimeter','']],[['ace_earplugs',true]]]";
    };
    class GVAR(loadout_groundIrs) {
        name = "Ground: IRS";
        loadout = "[[['arifle_mas_ukl_SPAR_01_blk_F','CUP_muzzle_snds_M16','CUP_acc_ANPEQ_15_Flashlight_Black_L','CUP_optic_Elcan_SpecterDR_RMR_black',['UK3CB_BAF_556_30Rnd',30],[],''],[],['UK3CB_BAF_L131A1','','UK3CB_BAF_Flashlight_L131A1','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_B_GhillieSuit',[['ACE_CableTie',2],['ACE_EarPlugs',1],['ACE_DefusalKit',1],['ACE_EntrenchingTool',1],['ACE_Flashlight_XL50',1],['ACE_MapTools',1],['ACE_microDAGR',1],['ACE_packingBandage',10],['ACE_IR_Strobe_Item',1],['ItemcTabHCam',1],['ACE_splint',2],['ACE_tourniquet',4],['ACE_elasticBandage',10],['acex_intelitems_notepad',1,1]]],['CUP_V_CPC_light_mc',[['B_IR_Grenade',2,1],['UK3CB_BAF_556_30Rnd',6,30],['UK3CB_BAF_9_17Rnd',2,17],['ACE_M84',2,1],['ACE_Chemlight_IR',3,1]]],['B_Kitbag_mcamo',[['NVGoggles_mas_ukl_hv18',1],['ACE_wirecutter',1],['UK3CB_BAF_SmokeShellBlue',1,1],['UK3CB_BAF_SmokeShellGreen',1,1],['UK3CB_BAF_SmokeShellOrange',1,1],['UK3CB_BAF_SmokeShellPurple',1,1],['UK3CB_BAF_SmokeShellRed',1,1],['UK3CB_BAF_SmokeShellYellow',1,1],['UK3CB_BAF_SmokeShell',2,1],['APERSTripMine_Wire_Mag',2,1]]],'H_mas_ukl_opscorn','G_mas_ukl_shemag',['ACE_Vector','','','',[],[],''],['ItemMap','ItemGPS','','ItemCompass','ACE_Altimeter','']],[['ace_earplugs',true]]]";
    };
    class GVAR(loadout_groundDive) {
        name = "Ground: Dive";
        loadout = "[[['arifle_mas_ukl_SDAR_F','CUP_muzzle_snds_M16','CUP_acc_ANPEQ_15_Flashlight_Black_L','CUP_optic_Elcan_SpecterDR_RMR_black',['30Rnd_mas_ukl_556x45UW_Stanag',30],[],''],[],['UK3CB_BAF_L131A1','','UK3CB_BAF_Flashlight_L131A1','',['UK3CB_BAF_9_17Rnd',17],[],''],['U_mas_ukl_B_Wetsuit',[['ACE_Flashlight_MX991',1],['ACE_tourniquet',4],['ACE_M26_Clacker',1],['ACE_CableTie',5],['ACE_EarPlugs',1],['ACE_packingBandage',10],['ACE_elasticBandage',10],['ACE_IR_Strobe_Item',1],['ACE_splint',2],['ACRE_PRC343',1],['ACRE_PRC152',1],['UK3CB_BAF_9_17Rnd',2,17],['ACE_Chemlight_UltraHiOrange',3,1],['ACE_Chemlight_IR',4,1]]],['V_RebreatherB',[]],['uksf_diving_bag',[['ACE_bloodIV_500',1],['DemoCharge_Remote_Mag',1,1],['CUP_HandGrenade_L109A2_HE',1,1],['UK3CB_BAF_SmokeShell',4,1],['UK3CB_BAF_SmokeShellGreen',2,1],['ACE_M84',2,1],['UK3CB_BAF_556_30Rnd_T',5,30],['30Rnd_mas_ukl_556x45UW_Stanag',5,30],['V_mas_ukl_PlateCarrierRF_rgr',false],['U_mas_ukl_B_CombatUniform_mtp',false]]],'H_mas_ukl_opscore_g','G_B_Diving',['ACE_Vector','','','',[],[],''],['ItemMap','ItemAndroid','','ItemCompass','ACE_Altimeter','NVGoggles_mas_ukl_hv18']],[['ace_earplugs',true]]]";
    };
};
// copyToClipboard str (getUnitLoadout player)
