#define MAIN_OP_MAGAZINES \
    "1Rnd_HE_Grenade_shell", \
    "1Rnd_SmokeBlue_Grenade_shell", \
    "1Rnd_SmokeGreen_Grenade_shell", \
    "1Rnd_SmokeOrange_Grenade_shell", \
    "1Rnd_SmokePurple_Grenade_shell", \
    "1Rnd_SmokeRed_Grenade_shell", \
    "1Rnd_SmokeYellow_Grenade_shell", \
    "1Rnd_Smoke_Grenade_shell", \
    "20Rnd_762x51_Mag", \
    "30Rnd_556x45_Stanag_red", \
    "30Rnd_556x45_Stanag_Tracer_Red", \
    "ACE_20Rnd_762x51_M118LR_Mag", \
    "ACE_20Rnd_762x51_M993_AP_Mag", \
    "ACE_20Rnd_762x51_Mag_Tracer", \
    "ACE_20Rnd_762x51_Mag_Tracer_Dim", \
    "ACE_20Rnd_762x51_Mk316_Mod_0_Mag", \
    "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", \
    "ACE_Chemlight_HiBlue", \
    "ACE_Chemlight_HiGreen", \
    "ACE_Chemlight_UltraHiOrange", \
    "ACE_Chemlight_HiRed", \
    "ACE_Chemlight_HiWhite", \
    "ACE_Chemlight_HiYellow", \
    "ACE_Chemlight_IR", \
    "ACE_Chemlight_Orange", \
    "ACE_Chemlight_Shield", \
    "ACE_Chemlight_White", \
    "ACE_HandFlare_Green", \
    "ACE_HandFlare_Red", \
    "ACE_HandFlare_White", \
    "ACE_HandFlare_Yellow", \
    "ACE_HuntIR_M203", \
    "ACE_M14", \
    "APERSBoundingMine_Range_Mag", \
    "APERSMine_Range_Mag", \
    "APERSTripMine_Wire_Mag", \
    "ATMine_Range_Mag", \
    "B_IR_Grenade", \
    "BreachCharge_Remote_Mag", \
    "CUP_1Rnd_StarCluster_Green_M203", \
    "CUP_1Rnd_StarCluster_Red_M203", \
    "CUP_1Rnd_StarCluster_White_M203", \
    "CUP_1Rnd_StarFlare_Green_M203", \
    "CUP_1Rnd_StarFlare_Red_M203", \
    "CUP_1Rnd_StarFlare_White_M203", \
    "CUP_HandGrenade_L109A1_HE", \
    "CUP_HandGrenade_L109A2_HE", \
    "CUP_HandGrenade_M67", \
    "CUP_MineE_M", \
    "CUP_Mine_M", \
    "CUP_PipeBomb_M", \
    "CUP_Stinger_M", \
    "Chemlight_red", \
    "ClaymoreDirectionalMine_Remote_Mag", \
    "DemoCharge_Remote_Mag", \
    "HandGrenade", \
    "Laserbatteries", \
    "MiniGrenade", \
    "SLAMDirectionalMine_Wire_Mag", \
    "SatchelCharge_Remote_Mag", \
    "SmokeShell", \
    "SmokeShellBlue", \
    "SmokeShellGreen", \
    "SmokeShellOrange", \
    "SmokeShellPurple", \
    "SmokeShellRed", \
    "SmokeShellYellow", \
    "UGL_FlareCIR_F", \
    "UGL_FlareGreen_F", \
    "UGL_FlareRed_F", \
    "UGL_FlareWhite_F", \
    "UGL_FlareYellow_F", \
    "UK3CB_BAF_127_100Rnd", \
    "UK3CB_BAF_127_10Rnd", \
    "UK3CB_BAF_127_10Rnd_AP", \
    "UK3CB_BAF_127_10Rnd_T", \
    "UK3CB_BAF_12G_Pellets", \
    "UK3CB_BAF_12G_Slugs", \
    "UK3CB_BAF_1Rnd_60mm_Mo_AB_Shells", \
    "UK3CB_BAF_1Rnd_60mm_Mo_Flare_White", \
    "UK3CB_BAF_1Rnd_60mm_Mo_Shells", \
    "UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White", \
    "UK3CB_BAF_1Rnd_60mm_Mo_WPSmoke_White", \
    "UK3CB_BAF_1Rnd_81mm_Mo_AB_Shells", \
    "UK3CB_BAF_1Rnd_81mm_Mo_Flare_White", \
    "UK3CB_BAF_1Rnd_81mm_Mo_IRFlare_White", \
    "UK3CB_BAF_1Rnd_81mm_Mo_Shells", \
    "UK3CB_BAF_1Rnd_81mm_Mo_Smoke_White", \
    "UK3CB_BAF_1Rnd_81mm_Mo_WPSmoke_White", \
    "UK3CB_BAF_1Rnd_HEDP_Grenade_Shell", \
    "UK3CB_BAF_1Rnd_HE_Grenade_Shell", \
    "UK3CB_BAF_1Rnd_SmokeBlue_Grenade_shell", \
    "UK3CB_BAF_1Rnd_SmokeGreen_Grenade_shell", \
    "UK3CB_BAF_1Rnd_SmokeOrange_Grenade_shell", \
    "UK3CB_BAF_1Rnd_SmokePurple_Grenade_shell", \
    "UK3CB_BAF_1Rnd_SmokeRed_Grenade_shell", \
    "UK3CB_BAF_1Rnd_SmokeYellow_Grenade_shell", \
    "UK3CB_BAF_1Rnd_Smoke_Grenade_shell", \
    "UK3CB_BAF_32Rnd_40mm_G_Box", \
    "UK3CB_BAF_338_5Rnd", \
    "UK3CB_BAF_338_5Rnd_Tracer", \
    "UK3CB_BAF_556_100Rnd", \
    "UK3CB_BAF_556_100Rnd_T", \
    "UK3CB_BAF_556_200Rnd", \
    "UK3CB_BAF_556_200Rnd_T", \
    "UK3CB_BAF_556_30Rnd", \
    "UK3CB_BAF_556_30Rnd_T", \
    "UK3CB_BAF_762_100Rnd", \
    "UK3CB_BAF_762_100Rnd_EL", \
    "UK3CB_BAF_762_100Rnd_T", \
    "UK3CB_BAF_762_100Rnd_T_EL", \
    "UK3CB_BAF_762_200Rnd", \
    "UK3CB_BAF_762_200Rnd_EL", \
    "UK3CB_BAF_762_200Rnd_T", \
    "UK3CB_BAF_762_200Rnd_T_EL", \
    "UK3CB_BAF_762_20Rnd", \
    "UK3CB_BAF_762_20Rnd_T", \
    "UK3CB_BAF_762_L42A1_20Rnd", \
    "UK3CB_BAF_762_L42A1_20Rnd_T", \
    "UK3CB_BAF_9_13Rnd", \
    "UK3CB_BAF_9_15Rnd", \
    "UK3CB_BAF_9_17Rnd", \
    "UK3CB_BAF_SmokeShell", \
    "UK3CB_BAF_SmokeShellBlue", \
    "UK3CB_BAF_SmokeShellGreen", \
    "UK3CB_BAF_SmokeShellOrange", \
    "UK3CB_BAF_SmokeShellPurple", \
    "UK3CB_BAF_SmokeShellRed", \
    "UK3CB_BAF_SmokeShellYellow", \
    "UK3CB_BAF_UGL_FlareCIR_F", \
    "UK3CB_BAF_UGL_FlareGreen_F", \
    "UK3CB_BAF_UGL_FlareRed_F", \
    "UK3CB_BAF_UGL_FlareWhite_F", \
    "UK3CB_BAF_UGL_FlareYellow_F", \
    "uksf_persistence_marker", \
    "SSQN_5Rnd_127x99", \
    "SSQN_5Rnd_127x99_HEIAP", \
    "SSQN_5Rnd_127x99_Tracer", \
    "SSQN_5Rnd_127x99_HEIAP_Tracer"

#define MAIN_OP_WEAPONS \
    "ACE_MX2A", \
    "ACE_SpottingScope", \
    "ACE_TacticalLadder_Pack", \
    "ACE_Tripod", \
    "ACE_VMH3", \
    "ACE_VMM3", \
    "ACE_Vector", \
    "ACE_VectorDay", \
    "ACE_Yardage450", \
    "Binocular", \
    "CUP_launch_FIM92Stinger", \
    "Rangefinder", \
    "UK3CB_BAF_AT4_CS_AP_Launcher", \
    "UK3CB_BAF_AT4_CS_AT_Launcher", \
    "UK3CB_BAF_Javelin_Slung_Tube", \
    "UK3CB_BAF_L105A2", \
    "UK3CB_BAF_L110A1", \
    "UK3CB_BAF_L110A2", \
    "UK3CB_BAF_L110A2RIS", \
    "UK3CB_BAF_L110A3", \
    "UK3CB_BAF_L111A1", \
    "UK3CB_BAF_L115A3", \
    "UK3CB_BAF_L115A3_BL", \
    "UK3CB_BAF_L115A3_BL_Ghillie", \
    "UK3CB_BAF_L115A3_DE", \
    "UK3CB_BAF_L115A3_DE_Ghillie", \
    "UK3CB_BAF_L115A3_Ghillie", \
    "UK3CB_BAF_L117A2", \
    "UK3CB_BAF_L118A1_Covert", \
    "UK3CB_BAF_L118A1_Covert_BL", \
    "UK3CB_BAF_L118A1_Covert_DE", \
    "UK3CB_BAF_L128A1", \
    "UK3CB_BAF_L129A1", \
    "UK3CB_BAF_L131A1", \
    "UK3CB_BAF_L134A1", \
    "UK3CB_BAF_L135A1", \
    "UK3CB_BAF_L16", \
    "UK3CB_BAF_L16_Tripod", \
    "UK3CB_BAF_L22A2", \
    "UK3CB_BAF_L7A2", \
    "UK3CB_BAF_L85A2", \
    "UK3CB_BAF_L85A2_RIS", \
    "UK3CB_BAF_L85A2_RIS_AFG", \
    "UK3CB_BAF_L85A2_RIS_AFG_Green", \
    "UK3CB_BAF_L85A2_RIS_AFG_Tan", \
    "UK3CB_BAF_L85A2_RIS_Green", \
    "UK3CB_BAF_L85A2_RIS_Tan", \
    "UK3CB_BAF_L85A2_UGL", \
    "UK3CB_BAF_L85A2_UGL_HWS", \
    "UK3CB_BAF_L85A3", \
    "UK3CB_BAF_L85A3_AFG", \
    "UK3CB_BAF_L85A3_AFG_D", \
    "UK3CB_BAF_L85A3_AFG_G", \
    "UK3CB_BAF_L85A3_AFG_T", \
    "UK3CB_BAF_L85A3_AFG_W", \
    "UK3CB_BAF_L85A3_Grippod", \
    "UK3CB_BAF_L85A3_Grippod_D", \
    "UK3CB_BAF_L85A3_Grippod_G", \
    "UK3CB_BAF_L85A3_Grippod_T", \
    "UK3CB_BAF_L85A3_Grippod_W", \
    "UK3CB_BAF_L85A3_UGL", \
    "UK3CB_BAF_L9A1", \
    "UK3CB_BAF_M6", \
    "UK3CB_BAF_NLAW_Launcher", \
    "UK3CB_BAF_Soflam_Laserdesignator", \
    "SSQN_L119A1_CQB", \
    "SSQN_L119A1_CQB_C1", \
    "SSQN_L119A1_CQB_C2", \
    "SSQN_L119A1_CQB_C3", \
    "SSQN_L119A1_CQB_v2", \
    "SSQN_L119A1_CQB_v2_C1", \
    "SSQN_L119A1_CQB_v2_C2", \
    "SSQN_L119A1_CQB_v2_C3", \
    "SSQN_L119A1_SFW", \
    "SSQN_L119A1_SFW_C1", \
    "SSQN_L119A1_SFW_C2", \
    "SSQN_L119A1_SFW_C3", \
    "SSQN_L119A1_SFW_v2", \
    "SSQN_L119A1_SFW_v2_C1", \
    "SSQN_L119A1_SFW_v2_C2", \
    "SSQN_L119A1_SFW_v2_C3", \
    "SSQN_L110A1", \
    "SSQN_L110A1_C1", \
    "SSQN_L110A1_C2", \
    "SSQN_L110A1_C3", \
    "SSQN_L110A1_CQB", \
    "SSQN_L110A1_CQB_C1", \
    "SSQN_L110A1_CQB_C2", \
    "SSQN_L110A1_CQB_C3", \
    "UK3CB_BAF_L119A1_UKUGL", \
    "SSQN_AW50"

#define MAIN_OP_ATTACHMENTS \
    "RKSL_optic_LDS", \
    "RKSL_optic_LDS_C", \
    "RKSL_optic_PMII_312", \
    "RKSL_optic_PMII_312_des", \
    "RKSL_optic_PMII_312_sunshade", \
    "RKSL_optic_PMII_312_sunshade_des", \
    "RKSL_optic_PMII_312_sunshade_wdl", \
    "RKSL_optic_PMII_312_wdl", \
    "RKSL_optic_PMII_525", \
    "RKSL_optic_PMII_525_des", \
    "RKSL_optic_PMII_525_wdl", \
    "RKSL_optic_PMII_525_NV", \
    "UK3CB_BAF_Flashlight_L131A1", \
    "UK3CB_BAF_Kite", \
    "UK3CB_BAF_LLM_Flashlight_Black", \
    "UK3CB_BAF_LLM_Flashlight_Far_Black", \
    "UK3CB_BAF_LLM_IR_Black", \
    "UK3CB_BAF_MaxiKite", \
    "UK3CB_BAF_Silencer_L110", \
    "UK3CB_BAF_Silencer_L115A3", \
    "UK3CB_BAF_Silencer_L85", \
    "UK3CB_BAF_SpecterLDS", \
    "UK3CB_BAF_SpecterLDS_3D", \
    "UK3CB_BAF_SpecterLDS_Dot_3D", \
    "UK3CB_BAF_TA648", \
    "UK3CB_BAF_TA648_308", \
    "UK3CB_BAF_Tripod", \
    "UK3CB_underbarrel_acc_afg", \
    "UK3CB_underbarrel_acc_bipod", \
    "UK3CB_underbarrel_acc_fgrip", \
    "UK3CB_underbarrel_acc_fgrip_bipod", \
    "UK3CB_underbarrel_acc_grippod", \
    "acc_pointer_IR", \
    "muzzle_snds_L", \
    "uk3cb_baf_flashlight_l105a1", \
    "uk3cb_baf_l105a1_llm_ir_g", \
    "uk3cb_baf_l105a1_llm_ir_r", \
    "uk3cb_baf_silencer_l105a1", \
    "SSQN_FA556212_Suppressor", \
    "SSQN_FA556212_Suppressor_C1", \
    "SSQN_FA556212_Suppressor_C2", \
    "SSQN_FA556212_Suppressor_C3", \
    "SSQN_BFA", \
    "SSQN_AR_ACOG", \
    "SSQN_AR_ACOG_C1", \
    "SSQN_AR_ACOG_C2", \
    "SSQN_AR_ACOG_C3", \
    "SSQN_AR_ACOG_DR", \
    "SSQN_AR_ACOG_DR_C1", \
    "SSQN_AR_ACOG_DR_C2", \
    "SSQN_AR_ACOG_DR_C3", \
    "SSQN_AR_AimpointCompM4", \
    "SSQN_AR_AimpointCompM4_C1", \
    "SSQN_AR_AimpointCompM4_C2", \
    "SSQN_AR_AimpointCompM4_C3", \
    "SSQN_AR_AimpointCompM4_Mag_OFF", \
    "SSQN_AR_AimpointCompM4_Mag_OFF_C1", \
    "SSQN_AR_AimpointCompM4_Mag_OFF_C2", \
    "SSQN_AR_AimpointCompM4_Mag_OFF_C3", \
    "SSQN_AR_AimpointCompM4_Mag_ON", \
    "SSQN_AR_AimpointCompM4_Mag_ON_C1", \
    "SSQN_AR_AimpointCompM4_Mag_ON_C2", \
    "SSQN_AR_AimpointCompM4_Mag_ON_C3", \
    "SSQN_AR_AimpointMicroT1", \
    "SSQN_AR_AimpointMicroT1_C1", \
    "SSQN_AR_AimpointMicroT1_C2", \
    "SSQN_AR_AimpointMicroT1_C3", \
    "SSQN_AR_AimpointMicroT1_CQB", \
    "SSQN_AR_AimpointMicroT1_CQB_C1", \
    "SSQN_AR_AimpointMicroT1_CQB_C2", \
    "SSQN_AR_AimpointMicroT1_CQB_C3", \
    "SSQN_AR_EOTech553", \
    "SSQN_AR_EOTech553_C1", \
    "SSQN_AR_EOTech553_C2", \
    "SSQN_AR_EOTech553_C3", \
    "SSQN_AR_EOTech553_CQB", \
    "SSQN_AR_EOTech553_CQB_C1", \
    "SSQN_AR_EOTech553_CQB_C2", \
    "SSQN_AR_EOTech553_CQB_C3", \
    "SSQN_AR_EOTech553_Mag_OFF", \
    "SSQN_AR_EOTech553_Mag_OFF_C1", \
    "SSQN_AR_EOTech553_Mag_OFF_C2", \
    "SSQN_AR_EOTech553_Mag_OFF_C3", \
    "SSQN_AR_EOTech553_Mag_ON", \
    "SSQN_AR_EOTech553_Mag_ON_C1", \
    "SSQN_AR_EOTech553_Mag_ON_C2", \
    "SSQN_AR_EOTech553_Mag_ON_C3", \
    "SSQN_RailCovers_3", \
    "SSQN_RailCovers_3_C1", \
    "SSQN_RailCovers_3_C2", \
    "SSQN_RailCovers_3_C3", \
    "SSQN_RailCovers_2", \
    "SSQN_RailCovers_2_C1", \
    "SSQN_RailCovers_2_C2", \
    "SSQN_RailCovers_2_C3", \
    "SSQN_Flashlight_RC", \
    "SSQN_Flashlight_RC_C1", \
    "SSQN_Flashlight_RC_C2", \
    "SSQN_Flashlight_RC_C3", \
    "SSQN_Flashlight", \
    "SSQN_Flashlight_C1", \
    "SSQN_Flashlight_C2", \
    "SSQN_Flashlight_C3", \
    "SSQN_PEQ_R_RC", \
    "SSQN_PEQ_R_RC_C1", \
    "SSQN_PEQ_R_RC_C2", \
    "SSQN_PEQ_R_RC_C3", \
    "SSQN_PEQ_R", \
    "SSQN_PEQ_R_C1", \
    "SSQN_PEQ_R_C2", \
    "SSQN_PEQ_R_C3", \
    "SSQN_PEQ_R_NoSwitch", \
    "SSQN_PEQ_R_NoSwitch_C1", \
    "SSQN_PEQ_R_NoSwitch_C2", \
    "SSQN_PEQ_R_NoSwitch_C3", \
    "SSQN_PEQ_T_RC", \
    "SSQN_PEQ_T_RC_C1", \
    "SSQN_PEQ_T_RC_C2", \
    "SSQN_PEQ_T_RC_C3", \
    "SSQN_PEQ_T", \
    "SSQN_PEQ_T_C1", \
    "SSQN_PEQ_T_C2", \
    "SSQN_PEQ_T_C3", \
    "SSQN_PEQ_T_NoSwitch", \
    "SSQN_PEQ_T_NoSwitch_C1", \
    "SSQN_PEQ_T_NoSwitch_C2", \
    "SSQN_PEQ_T_NoSwitch_C3", \
    "SSQN_PEQ_Flashlight", \
    "SSQN_PEQ_Flashlight_C1", \
    "SSQN_PEQ_Flashlight_C2", \
    "SSQN_PEQ_Flashlight_C3", \
    "SSQN_Flashlight_PEQ", \
    "SSQN_Flashlight_PEQ_C1", \
    "SSQN_Flashlight_PEQ_C2", \
    "SSQN_Flashlight_PEQ_C3", \
    "SSQN_PEQ_Flashlight_RC", \
    "SSQN_PEQ_Flashlight_RC_C1", \
    "SSQN_PEQ_Flashlight_RC_C2", \
    "SSQN_PEQ_Flashlight_RC_C3", \
    "SSQN_Flashlight_PEQ_RC", \
    "SSQN_Flashlight_PEQ_RC_C1", \
    "SSQN_Flashlight_PEQ_RC_C2", \
    "SSQN_Flashlight_PEQ_RC_C3", \
    "SSQN_PEQ_Flashlight_RC_NoSwitch", \
    "SSQN_PEQ_Flashlight_RC_NoSwitch_C1", \
    "SSQN_PEQ_Flashlight_RC_NoSwitch_C2", \
    "SSQN_PEQ_Flashlight_RC_NoSwitch_C3", \
    "SSQN_Flashlight_PEQ_RC_NoSwitch", \
    "SSQN_Flashlight_PEQ_RC_NoSwitch_C1", \
    "SSQN_Flashlight_PEQ_RC_NoSwitch_C2", \
    "SSQN_Flashlight_PEQ_RC_NoSwitch_C3", \
    "SSQN_PEQ_Flashlight_NoSwitch", \
    "SSQN_PEQ_Flashlight_NoSwitch_C1", \
    "SSQN_PEQ_Flashlight_NoSwitch_C2", \
    "SSQN_PEQ_Flashlight_NoSwitch_C3", \
    "SSQN_Flashlight_PEQ_NoSwitch", \
    "SSQN_Flashlight_PEQ_NoSwitch_C1", \
    "SSQN_Flashlight_PEQ_NoSwitch_C2", \
    "SSQN_Flashlight_PEQ_NoSwitch_C3", \
    "SSQN_FA556MG_Suppressor", \
    "SSQN_FA556MG_Suppressor_C1", \
    "SSQN_FA556MG_Suppressor_C2", \
    "SSQN_FA556MG_Suppressor_C3", \
    "SSQN_FA556MG_Suppressor_C4", \
    "SSQN_FiftyCal_Suppressor", \
    "CUP_optic_Elcan_SpecterDR_RMR_black", \
    "CUP_optic_Elcan_SpecterDR_RMR_coyote", \
    "CUP_optic_Elcan_SpecterDR_RMR_od", \
    "CUP_optic_Elcan_SpecterDR_RMR"

#define MAIN_OP_NVGS \
    "ACE_NVG_Pilot", \
    "CUP_NVG_PVS15_black", \
    "CUP_NVG_PVS15_green", \
    "CUP_NVG_PVS15_tan", \
    "CUP_NVG_PVS15_winter", \
    "UK3CB_BAF_HMNVS"

#define MAIN_OP_ITEMS \
    "ACE_ATragMX", \
    "ACE_Altimeter", \
    "ACE_CableTie", \
    "ACE_Clacker", \
    "ACE_DAGR", \
    "ACE_DefusalKit", \
    "ACE_EarPlugs", \
    "ACE_EntrenchingTool", \
    "ACE_Flashlight_KSF1", \
    "ACE_Flashlight_MX991", \
    "ACE_Flashlight_XL50", \
    "ACE_HuntIR_monitor", \
    "ACE_Kestrel4500", \
    "ACE_M26_Clacker", \
    "ACE_M84", \
    "ACE_MapTools", \
    "ACE_RangeCard", \
    "ACE_RangeTable_82mm", \
    "ACE_Sandbag_empty", \
    "ACE_SpraypaintBlack", \
    "ACE_SpraypaintBlue", \
    "ACE_SpraypaintGreen", \
    "ACE_SpraypaintRed", \
    "ACE_adenosine", \
    "ACE_atropine", \
    "ACE_bloodIV", \
    "ACE_bloodIV_250", \
    "ACE_bloodIV_500", \
    "ACE_bodyBag", \
    "ACE_elasticBandage", \
    "ACE_epinephrine", \
    "ACE_fieldDressing", \
    "ACE_microDAGR", \
    "ACE_morphine", \
    "ACE_packingBandage", \
    "ACE_painkillers", \
    "ACE_penTorch", \
    "ACE_personalAidKit", \
    "ACE_plasmaIV", \
    "ACE_plasmaIV_250", \
    "ACE_plasmaIV_500", \
    "ACE_quikclot", \
    "ACE_salineIV", \
    "ACE_salineIV_250", \
    "ACE_salineIV_500", \
    "ACE_splint", \
    "ACE_surgicalKit", \
    "ACE_tourniquet", \
    "ACE_wirecutter", \
    "ACRE_PRC117F", \
    "ACRE_PRC152", \
    "ACRE_PRC343", \
    "B_UavTerminal", \
    "ItemCompass", \
    "ItemGPS", \
    "ItemMap", \
    "ItemWatch", \
    "ToolKit", \
    "UK3CB_BAF_Javelin_CLU", \
    "uksf_atc_terminal", \
    "ItemAndroid"

#define MAIN_OP_UNIFORMS \
    "SP_0000_Standard_TacticalUniform_ATacsFG", \
    "SP_0000_Standard_TacticalUniform_ATacsFG_SS", \
    "UK3CB_BAF_U_CombatUniform_Arctic_Ghillie_RM", \
    "UK3CB_BAF_U_CombatUniform_DDPM", \
    "UK3CB_BAF_U_CombatUniform_DDPM_Ghillie_RM", \
    "UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve", \
    "UK3CB_BAF_U_CombatUniform_DPMT", \
    "UK3CB_BAF_U_CombatUniform_DPMT_Ghillie_RM", \
    "UK3CB_BAF_U_CombatUniform_DPMT_ShortSleeve", \
    "UK3CB_BAF_U_CombatUniform_DPMW", \
    "UK3CB_BAF_U_CombatUniform_DPMW_Ghillie_RM", \
    "UK3CB_BAF_U_CombatUniform_DPMW_ShortSleeve", \
    "UK3CB_BAF_U_CombatUniform_MTP_1Para", \
    "UK3CB_BAF_U_CombatUniform_MTP_1Para_ShortSleeve", \
    "UK3CB_BAF_U_CombatUniform_MTP_CSMR", \
    "UK3CB_BAF_U_CombatUniform_MTP_CSMR_ShortSleeve", \
    "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM", \
    "UK3CB_BAF_U_CombatUniform_MTP_Path", \
    "UK3CB_BAF_U_CombatUniform_MTP_Path_ShortSleeve", \
    "UK3CB_BAF_U_CombatUniform_MTP_Sig", \
    "UK3CB_BAF_U_CombatUniform_MTP_Sig_ShortSleeve", \
    "UK3CB_BAF_U_CombatUniform_MTP_TShirt", \
    "UK3CB_BAF_U_Smock_Arctic", \
    "UKSF_U_PilotCoveralls_7", \
    "UKSF_U_PilotGSuit_617", \
    "UKSF_U_PilotUniform_656", \
    "UKSF_U_RAF_Blues", \
    "U_B_FullGhillie_ard", \
    "U_B_FullGhillie_lsh", \
    "U_B_FullGhillie_sard", \
    "U_B_GhillieSuit", \
    "U_B_T_FullGhillie_tna_F", \
    "U_B_T_Sniper_F", \
    "VSM_Multicam_Crye_Camo", \
    "VSM_Multicam_Crye_SS_Camo", \
    "Alpine_Crye_Camo", \
    "Black_Black_Camo", \
    "Black_Black_SS_Camo", \
    "black_Crye_Camo", \
    "Multicam_black_casual_Camo", \
    "Black_Crye_SS_Camo", \
    "black_Crye2_Camo", \
    "U_B_Wetsuit", \
    "U_B_survival_uniform"

#define MAIN_OP_VESTS \
    "UK3CB_BAF_V_HiVis", \
    "UK3CB_BAF_V_Osprey", \
    "UK3CB_BAF_V_Osprey_Belt_A", \
    "UK3CB_BAF_V_Osprey_DDPM1", \
    "UK3CB_BAF_V_Osprey_DDPM2", \
    "UK3CB_BAF_V_Osprey_DDPM3", \
    "UK3CB_BAF_V_Osprey_DDPM4", \
    "UK3CB_BAF_V_Osprey_DDPM5", \
    "UK3CB_BAF_V_Osprey_DDPM6", \
    "UK3CB_BAF_V_Osprey_DDPM7", \
    "UK3CB_BAF_V_Osprey_DDPM8", \
    "UK3CB_BAF_V_Osprey_DDPM9", \
    "UK3CB_BAF_V_Osprey_DPMT1", \
    "UK3CB_BAF_V_Osprey_DPMT2", \
    "UK3CB_BAF_V_Osprey_DPMT3", \
    "UK3CB_BAF_V_Osprey_DPMT4", \
    "UK3CB_BAF_V_Osprey_DPMT5", \
    "UK3CB_BAF_V_Osprey_DPMT6", \
    "UK3CB_BAF_V_Osprey_DPMT7", \
    "UK3CB_BAF_V_Osprey_DPMT8", \
    "UK3CB_BAF_V_Osprey_DPMT9", \
    "UK3CB_BAF_V_Osprey_DPMW1", \
    "UK3CB_BAF_V_Osprey_DPMW2", \
    "UK3CB_BAF_V_Osprey_DPMW3", \
    "UK3CB_BAF_V_Osprey_DPMW4", \
    "UK3CB_BAF_V_Osprey_DPMW5", \
    "UK3CB_BAF_V_Osprey_DPMW6", \
    "UK3CB_BAF_V_Osprey_DPMW7", \
    "UK3CB_BAF_V_Osprey_DPMW8", \
    "UK3CB_BAF_V_Osprey_DPMW9", \
    "UK3CB_BAF_V_Osprey_Grenadier_A", \
    "UK3CB_BAF_V_Osprey_Grenadier_B", \
    "UK3CB_BAF_V_Osprey_Holster", \
    "UK3CB_BAF_V_Osprey_Lite", \
    "UK3CB_BAF_V_Osprey_MG_A", \
    "UK3CB_BAF_V_Osprey_MG_B", \
    "UK3CB_BAF_V_Osprey_Marksman_A", \
    "UK3CB_BAF_V_Osprey_Medic_A", \
    "UK3CB_BAF_V_Osprey_Medic_B", \
    "UK3CB_BAF_V_Osprey_Medic_C", \
    "UK3CB_BAF_V_Osprey_Medic_D", \
    "UK3CB_BAF_V_Osprey_Rifleman_A", \
    "UK3CB_BAF_V_Osprey_Rifleman_B", \
    "UK3CB_BAF_V_Osprey_Rifleman_C", \
    "UK3CB_BAF_V_Osprey_Rifleman_D", \
    "UK3CB_BAF_V_Osprey_Rifleman_E", \
    "UK3CB_BAF_V_Osprey_Rifleman_F", \
    "UK3CB_BAF_V_Osprey_SL_A", \
    "UK3CB_BAF_V_Osprey_SL_B", \
    "UK3CB_BAF_V_Osprey_SL_C", \
    "UK3CB_BAF_V_Osprey_SL_D", \
    "UK3CB_BAF_V_Osprey_Winter", \
    "UK3CB_BAF_V_PLCE_Webbing_DDPM", \
    "UK3CB_BAF_V_PLCE_Webbing_DPMT", \
    "UK3CB_BAF_V_PLCE_Webbing_DPMW", \
    "UK3CB_BAF_V_PLCE_Webbing_MTP", \
    "UK3CB_BAF_V_PLCE_Webbing_OLI", \
    "UK3CB_BAF_V_PLCE_Webbing_Plate_DDPM", \
    "UK3CB_BAF_V_PLCE_Webbing_Plate_DPMT", \
    "UK3CB_BAF_V_PLCE_Webbing_Plate_DPMW", \
    "UK3CB_BAF_V_PLCE_Webbing_Plate_MTP", \
    "UK3CB_BAF_V_PLCE_Webbing_Plate_OLI", \
    "UK3CB_BAF_V_PLCE_Webbing_Plate_Winter", \
    "UK3CB_BAF_V_PLCE_Webbing_Winter", \
    "UK3CB_BAF_V_Pilot_A", \
    "UKSF_V_Pilot", \
    "VSM_LBT1961_Black", \
    "VSM_FAPC_MG_Multicam", \
    "VSM_FAPC_Operator_Multicam", \
    "VSM_CarrierRig_Gunner_Multicam", \
    "VSM_CarrierRig_Operator_Multicam", \
    "VSM_LBT6094_MG_Multicam", \
    "VSM_LBT6094_operator_Multicam", \
    "VSM_RAV_MG_Multicam", \
    "VSM_RAV_operator_Multicam", \
    "dr_ALPfacp_mg", \
    "dr_ALPfacp_op", \
    "dr_ALPlbt_mg", \
    "dr_ALPpar_mg", \
    "dr_ALPpar_op", \
    "dr_ALPlbt_op", \
    "dr_BLKfacp_mg", \
    "dr_BLKfacp_op", \
    "dr_BLKlbt_mg", \
    "dr_BLKlbt_op", \
    "dr_BLKpar_mg", \
    "dr_BLKpar_op", \
    "V_RebreatherB", \
    "V_RebreatherIA"

#define MAIN_OP_BACKPACKS \
    "B_AssaultPack_rgr", \
    "B_Kitbag_mcamo", \
    "B_Kitbag_rgr", \
    "B_Parachute", \
    "CUP_B_USMC_AssaultPack", \
    "ACE_NonSteerableParachute", \
    "SP_Carryall_ATacsAU", \
    "SP_Carryall_ATacsFG", \
    "SP_Carryall_Tan", \
    "STKR_MLode", \
    "STKR_PackCom", \
    "STKR_Predator", \
    "STKR_PredatorBow", \
    "UK3CB_BAF_B_Bergen_Arctic_JTAC_A", \
    "UK3CB_BAF_B_Bergen_Arctic_JTAC_H_A", \
    "UK3CB_BAF_B_Bergen_Arctic_Rifleman_A", \
    "UK3CB_BAF_B_Bergen_Arctic_Rifleman_B", \
    "UK3CB_BAF_B_Bergen_Arctic_SL_A", \
    "UK3CB_BAF_B_Bergen_DDPM_JTAC_A", \
    "UK3CB_BAF_B_Bergen_DDPM_JTAC_H_A", \
    "UK3CB_BAF_B_Bergen_DDPM_Rifleman_A", \
    "UK3CB_BAF_B_Bergen_DDPM_Rifleman_B", \
    "UK3CB_BAF_B_Bergen_DDPM_SL_A", \
    "UK3CB_BAF_B_Bergen_DPMT_JTAC_A", \
    "UK3CB_BAF_B_Bergen_DPMT_JTAC_H_A", \
    "UK3CB_BAF_B_Bergen_DPMT_Rifleman_A", \
    "UK3CB_BAF_B_Bergen_DPMT_Rifleman_B", \
    "UK3CB_BAF_B_Bergen_DPMT_SL_A", \
    "UK3CB_BAF_B_Bergen_DPMW_JTAC_A", \
    "UK3CB_BAF_B_Bergen_DPMW_JTAC_H_A", \
    "UK3CB_BAF_B_Bergen_DPMW_Rifleman_A", \
    "UK3CB_BAF_B_Bergen_DPMW_Rifleman_B", \
    "UK3CB_BAF_B_Bergen_DPMW_SL_A", \
    "UK3CB_BAF_B_Bergen_MTP_Engineer_H_A", \
    "UK3CB_BAF_B_Bergen_MTP_Engineer_L_A", \
    "UK3CB_BAF_B_Bergen_MTP_Engineer_L_A_Toolkit", \
    "UK3CB_BAF_B_Bergen_MTP_JTAC_H_A", \
    "UK3CB_BAF_B_Bergen_MTP_JTAC_L_A", \
    "UK3CB_BAF_B_Bergen_MTP_Medic_H_A", \
    "UK3CB_BAF_B_Bergen_MTP_Medic_H_B", \
    "UK3CB_BAF_B_Bergen_MTP_Medic_L_A", \
    "UK3CB_BAF_B_Bergen_MTP_Medic_L_B", \
    "UK3CB_BAF_B_Bergen_MTP_PointMan_H_A", \
    "UK3CB_BAF_B_Bergen_MTP_PointMan_L_A", \
    "UK3CB_BAF_B_Bergen_MTP_Radio_H_A", \
    "UK3CB_BAF_B_Bergen_MTP_Radio_H_B", \
    "UK3CB_BAF_B_Bergen_MTP_Radio_L_A", \
    "UK3CB_BAF_B_Bergen_MTP_Radio_L_B", \
    "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_A", \
    "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B", \
    "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_C", \
    "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_A", \
    "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_B", \
    "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C", \
    "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D", \
    "UK3CB_BAF_B_Bergen_MTP_Rifleman_XL_A", \
    "UK3CB_BAF_B_Bergen_MTP_SL_H_A", \
    "UK3CB_BAF_B_Bergen_MTP_SL_L_A", \
    "UK3CB_BAF_B_Bergen_MTP_Sapper_H_A", \
    "UK3CB_BAF_B_Bergen_MTP_Sapper_L_A", \
    "UK3CB_BAF_B_Bergen_OLI_JTAC_A", \
    "UK3CB_BAF_B_Bergen_OLI_JTAC_H_A", \
    "UK3CB_BAF_B_Bergen_OLI_Rifleman_A", \
    "UK3CB_BAF_B_Bergen_OLI_Rifleman_B", \
    "UK3CB_BAF_B_Bergen_OLI_SL_A", \
    "UK3CB_BAF_B_Bergen_TAN_JTAC_A", \
    "UK3CB_BAF_B_Bergen_TAN_JTAC_H_A", \
    "UK3CB_BAF_B_Bergen_TAN_Rifleman_A", \
    "UK3CB_BAF_B_Bergen_TAN_Rifleman_B", \
    "UK3CB_BAF_B_Bergen_TAN_SL_A", \
    "UK3CB_BAF_B_Carryall_Arctic", \
    "UK3CB_BAF_B_Carryall_DDPM", \
    "UK3CB_BAF_B_Carryall_DPMT", \
    "UK3CB_BAF_B_Carryall_DPMW", \
    "UK3CB_BAF_B_Carryall_MTP", \
    "UK3CB_BAF_B_Carryall_OLI", \
    "UK3CB_BAF_B_Carryall_TAN", \
    "UK3CB_BAF_B_Kitbag_Arctic", \
    "UK3CB_BAF_B_Kitbag_DDPM", \
    "UK3CB_BAF_B_Kitbag_DPMT", \
    "UK3CB_BAF_B_Kitbag_DPMW", \
    "UK3CB_BAF_B_Kitbag_MTP", \
    "UK3CB_BAF_B_Kitbag_OLI", \
    "UK3CB_BAF_B_Kitbag_TAN", \
    "UKSF_B_Bergen_Medic_DDPM", \
    "UKSF_B_Carryall_Mortar_MTP", \
    "VSM_Multicam_carryall", \
    "VSM_Multicam_Backpack_Compact", \
    "VSM_Multicam_Backpack_Kitbag", \
    "Alpine_Carryall", \
    "Alpine_Backpack_Compact", \
    "Alpine_backpack_kitbag", \
    "Black_Carryall", \
    "Black_Backpack_Compact", \
    "Black_Backpack_kitbag", \
    "tfw_ilbe_b", \
    "tfw_ilbe_w", \
    "tfw_ilbe_vsm", \
    "tfw_ilbe_a_b", \
    "tfw_ilbe_a_w", \
    "tfw_ilbe_a_vsm", \
    "tfw_ilbe_dd_b", \
    "tfw_ilbe_dd_w", \
    "tfw_ilbe_dd_vsm", \
    "tfw_ilbe_blade_b", \
    "tfw_ilbe_blade_w", \
    "tfw_ilbe_blade_vsm", \
    "B_MAV_B_BACKPACK"

#define MAIN_OP_HELMETS \
    "COVER_4b", \
    "COVER_4d", \
    "H_Bandanna_camo", \
    "H_Bandanna_cbr", \
    "H_Bandanna_khk", \
    "H_Bandanna_khk_hs", \
    "H_Bandanna_sand", \
    "H_Bonniehat_mcamo", \
    "H_Booniehat_mcamo", \
    "H_Booniehat_oli", \
    "H_Booniehat_tan", \
    "H_HelmetB_desert", \
    "H_HelmetB_light_snakeskin", \
    "H_PilotHelmetFighter_B", \
    "H_ShemagOpen_tan", \
    "H_Shemag_olive", \
    "H_Watchcap_khk", \
    "OPS_CORE_21", \
    "OPS_CORE_22", \
    "SP_BoonieHat_Green", \
    "SP_BoonieHat_Tan", \
    "SP_ECHHelmet_Green1", \
    "UK3CB_BAF_H_Beret_AAC", \
    "UK3CB_BAF_H_Beret_AAC_PRR", \
    "UK3CB_BAF_H_Beret_PR", \
    "UK3CB_BAF_H_Beret_PR_PRR", \
    "UK3CB_BAF_H_Beret_RAF", \
    "UK3CB_BAF_H_Beret_RAF_PRR", \
    "UK3CB_BAF_H_Beret_RAMC", \
    "UK3CB_BAF_H_Beret_RAMC_PRR", \
    "UK3CB_BAF_H_Beret_Signals", \
    "UK3CB_BAF_H_Beret_Signals_PRR", \
    "UK3CB_BAF_H_Boonie_DDPM", \
    "UK3CB_BAF_H_Boonie_DDPM_PRR", \
    "UK3CB_BAF_H_Boonie_DPMT", \
    "UK3CB_BAF_H_Boonie_DPMT_PRR", \
    "UK3CB_BAF_H_Boonie_DPMW", \
    "UK3CB_BAF_H_Boonie_DPMW_PRR", \
    "UK3CB_BAF_H_Boonie_MTP", \
    "UK3CB_BAF_H_Boonie_MTP_PRR", \
    "UK3CB_BAF_H_Mk6_DDPM_A", \
    "UK3CB_BAF_H_Mk6_DDPM_B", \
    "UK3CB_BAF_H_Mk6_DDPM_C", \
    "UK3CB_BAF_H_Mk6_DDPM_D", \
    "UK3CB_BAF_H_Mk6_DDPM_E", \
    "UK3CB_BAF_H_Mk6_DDPM_F", \
    "UK3CB_BAF_H_Mk6_DPMT_A", \
    "UK3CB_BAF_H_Mk6_DPMT_B", \
    "UK3CB_BAF_H_Mk6_DPMT_C", \
    "UK3CB_BAF_H_Mk6_DPMT_D", \
    "UK3CB_BAF_H_Mk6_DPMT_E", \
    "UK3CB_BAF_H_Mk6_DPMT_F", \
    "UK3CB_BAF_H_Mk6_DPMW_A", \
    "UK3CB_BAF_H_Mk6_DPMW_B", \
    "UK3CB_BAF_H_Mk6_DPMW_C", \
    "UK3CB_BAF_H_Mk6_DPMW_D", \
    "UK3CB_BAF_H_Mk6_DPMW_E", \
    "UK3CB_BAF_H_Mk6_DPMW_F", \
    "UK3CB_BAF_H_Mk7_Camo_A", \
    "UK3CB_BAF_H_Mk7_Camo_B", \
    "UK3CB_BAF_H_Mk7_Camo_C", \
    "UK3CB_BAF_H_Mk7_Camo_CESS_A", \
    "UK3CB_BAF_H_Mk7_Camo_CESS_B", \
    "UK3CB_BAF_H_Mk7_Camo_CESS_C", \
    "UK3CB_BAF_H_Mk7_Camo_CESS_D", \
    "UK3CB_BAF_H_Mk7_Camo_D", \
    "UK3CB_BAF_H_Mk7_Camo_E", \
    "UK3CB_BAF_H_Mk7_Camo_ESS_A", \
    "UK3CB_BAF_H_Mk7_Camo_ESS_B", \
    "UK3CB_BAF_H_Mk7_Camo_ESS_C", \
    "UK3CB_BAF_H_Mk7_Camo_ESS_D", \
    "UK3CB_BAF_H_Mk7_Camo_F", \
    "UK3CB_BAF_H_Mk7_Net_A", \
    "UK3CB_BAF_H_Mk7_Net_B", \
    "UK3CB_BAF_H_Mk7_Net_C", \
    "UK3CB_BAF_H_Mk7_Net_CESS_A", \
    "UK3CB_BAF_H_Mk7_Net_CESS_B", \
    "UK3CB_BAF_H_Mk7_Net_CESS_C", \
    "UK3CB_BAF_H_Mk7_Net_CESS_D", \
    "UK3CB_BAF_H_Mk7_Net_D", \
    "UK3CB_BAF_H_Mk7_Net_ESS_A", \
    "UK3CB_BAF_H_Mk7_Net_ESS_B", \
    "UK3CB_BAF_H_Mk7_Net_ESS_C", \
    "UK3CB_BAF_H_Mk7_Net_ESS_D", \
    "UK3CB_BAF_H_Mk7_Scrim_A", \
    "UK3CB_BAF_H_Mk7_Scrim_B", \
    "UK3CB_BAF_H_Mk7_Scrim_C", \
    "UK3CB_BAF_H_Mk7_Scrim_D", \
    "UK3CB_BAF_H_Mk7_Scrim_E", \
    "UK3CB_BAF_H_Mk7_Scrim_ESS_A", \
    "UK3CB_BAF_H_Mk7_Scrim_ESS_B", \
    "UK3CB_BAF_H_Mk7_Scrim_ESS_C", \
    "UK3CB_BAF_H_Mk7_Scrim_F", \
    "UK3CB_BAF_H_Mk7_Win_A", \
    "UK3CB_BAF_H_Mk7_Win_ESS_A", \
    "UK3CB_BAF_H_PilotHelmetHeli_A", \
    "VSM_Black_OPS", \
    "VSM_OPS_multicam", \
    "VSM_Black_OPS_2", \
    "VSM_OPS_2_multicam", \
    "ALP_opscore_2", \
    "BLK_opscore_2", \
    "WHT_opscore_2", \
    "ALP_opscore", \
    "BLK2_opscore", \
    "WHT_opscore"

#define MAIN_OP_GLASSES \
    "CUP_FR_NeckScarf", \
    "CUP_FR_NeckScarf2", \
    "CUP_H_FR_BandannaGreen", \
    "CUP_H_RUS_Bandana_HS", \
    "CUP_TK_NeckScarf", \
    "UK3CB_BAF_G_Tactical_Black", \
    "UK3CB_BAF_G_Tactical_Clear", \
    "UK3CB_BAF_G_Tactical_Grey", \
    "UK3CB_BAF_G_Tactical_Orange", \
    "UK3CB_BAF_G_Tactical_Yellow", \
    "G_B_Diving"

#define MAIN_OP_GEAR [MAIN_OP_MAGAZINES, MAIN_OP_WEAPONS, MAIN_OP_ATTACHMENTS, MAIN_OP_NVGS, MAIN_OP_ITEMS, MAIN_OP_UNIFORMS, MAIN_OP_VESTS, MAIN_OP_BACKPACKS, MAIN_OP_HELMETS, MAIN_OP_GLASSES]
