#define COMPONENT civilian
#define COMPONENT_BEAUTIFIED Civilian
#include "\u\uksf\addons\main\script_mod.hpp"

#define DEBUG_MODE_FULL
#define DISABLE_COMPILE_CACHE
#define CBA_DEBUG_SYNCHRONOUS

#include "\u\uksf\addons\main\script_macros.hpp"

#define GESTURE_COOLDOWN 1
#define GESTURE_VEHICLE_SEARCH_DISTANCE 100
#define GESTURE_UNIT_SEARCH_DISTANCE 50

#define VISION_ARC 60
#define VISION_ARC_WIDE 100

#define VEHICLE_STOP_IGNORE_CHANCE 10
#define VEHICLE_STOP_INTERVAL 1
#define VEHICLE_STOP_BOREDOM_INCREMENT_CHANCE 5

#define UNIT_STOP_WALK_TO_PLAYER_CHANCE 30
#define UNIT_STOP_IGNORE_CHANCE 5
#define UNIT_STOP_INTERVAL 1
#define UNIT_STOP_BOREDOM_INCREMENT_CHANCE 5

#define STOP_ANNOYED_THRESHOLD 50
#define STOP_BOREDOM_THRESHOLD 100
