#define COMPONENT civilian
#define COMPONENT_BEAUTIFIED Civilian
#include "\u\uksf\addons\main\script_mod.hpp"

#define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define CBA_DEBUG_SYNCHRONOUS

#include "\u\uksf\addons\main\script_macros.hpp"

#define GESTURE_COOLDOWN 1
#define GESTURE_VEHICLE_SEARCH_DISTANCE 100
#define GESTURE_VEHICLE_SEARCH_CLOSE_DISTANCE 15

#define VEHICLE_VISION_ARC 60
#define VEHICLE_VISION_ARC_WIDE 100

#define VEHICLE_STOP_IGNORE_CHANCE 10
#define VEHICLE_STOP_INTERVAL 5
#define VEHICLE_STOP_ANNOYED_THRESHOLD 50
#define VEHICLE_STOP_BOREDOM_INCREMENT_CHANCE 10
#define VEHICLE_STOP_BOREDOM_THRESHOLD 100

#define MAN_VISION_ARC 60
#define MAN_VISION_ARC_WIDE 100

#define MAN_STOP_IGNORE_CHANCE 1
#define MAN_STOP_INTERVAL 5
#define MAN_STOP_ANNOYED_THRESHOLD 50
#define MAN_STOP_BOREDOM_INCREMENT_CHANCE 5
#define MAN_STOP_BOREDOM_THRESHOLD 100
