PREP(fired);
PREP(firedPlayerForce);
PREP(firedPlayerRecoil);
PREP(firedShockwave);
PREP(firedTwitch);
PREP(readCacheValues);
PREP(shockwaveHandler);

SHOCKWAVEPREP(120mm);
SHOCKWAVEPREP(Arty);
SHOCKWAVEPREP(BigBomb);
SHOCKWAVEPREP(BigRocket);
SHOCKWAVEPREP(FuelExploBig);
SHOCKWAVEPREP(FuelExploSmall);
SHOCKWAVEPREP(Grenade);
SHOCKWAVEPREP(IED);
SHOCKWAVEPREP(Mortar);
SHOCKWAVEPREP(Satchel);
SHOCKWAVEPREP(SmallRocket);
