# Writes addons/common/common_compat_hitpoints from gendup/ and srcadd.txt (configSourceAddonList of each class).
import os, sys

root = sys.argv[1]
adds = []
for l in open('srcadd.txt', encoding='latin1'):
    for a in l.rstrip('\n').split('|')[2].split(','):
        # The modpack must not depend on uksf_air; uksf_air re-opens these classes with the same parents.
        if a and not a.startswith('uksf_air') and a != 'uksf_common_compat_hitpoints' and a not in adds:
            adds.append(a)
adds = ['uksf_common'] + sorted(a for a in adds if a != 'uksf_common')
d = os.path.join(root, 'addons', 'common', 'common_compat_hitpoints')
os.makedirs(d, exist_ok=True)
for f in os.listdir(d):
    if f.startswith('CfgVehicles_'):
        os.remove(os.path.join(d, f))
open(os.path.join(d, 'script_component.hpp'), 'w', newline='\n').write(
    '#define COMPONENT common_compat_hitpoints\n'
    '#include "\\u\\uksf\\addons\\main\\script_mod.hpp"\n'
    '#include "\\u\\uksf\\addons\\main\\script_macros.hpp"\n')
files = sorted(f for f in os.listdir('gendup') if f.endswith('.hpp'))
L = ['#include "script_component.hpp"', '',
     '// Generated by dev_harness/loadall/hitpoints: duplicate turret HitTurret, HitGun and HitCommanderTurret entries',
     "// whose selection the model's HitPoints LOD lacks, removed on the class that defines them. Where every copy",
     '// is dead, the first turret copy stays. Every class is re-opened with its own parent.',
     'class CfgPatches {', '    class ADDON {', '        name = COMPONENT_NAME;', '        units[] = {};',
     '        weapons[] = {};', '        requiredVersion = REQUIRED_VERSION;', '        requiredAddons[] = {']
L += ['            "%s",' % a for a in adds]
L += ['        };', '    };', '};', '', 'class CfgVehicles {'] + ['#include "%s"' % f for f in files] + ['};']
open(os.path.join(d, 'config.cpp'), 'w', newline='\n').write('\n'.join(L) + '\n')
for f in files:
    open(os.path.join(d, f), 'w', newline='\n').write(open(os.path.join('gendup', f)).read())
print('requiredAddons', len(adds), 'files', len(files))
