PREP(addCuratorActions);
PREP(curatorAssign);
PREP(curatorCreate);
PREP(curatorKick);
PREP(curatorLogin);
PREP(curatorLogout);
PREP(curatorUnassign);
PREP(getCuratorActions);
PREP(setCuratorsLocked);
