# Generates addons/common/common_compat_glass: window hitpoints for buildings whose model has glass_N hit,
# effects and fire-geometry selections and whose animation sources expect Glass_N_hitpoint, but whose config
# defines no HitPoints, so the windows never break. Also writes extra_hitpoints.json for gen_anims.py.
# Inputs: gl.txt (glass.sqf), gp.txt (glassparents.sqf), animsrc.txt, rootdata.txt, learned.json.
# Usage: python gen_glass.py <addon dir>
import json, os, re, sys, collections

LOD = {'HitPoints': 'H', 'Memory': 'M', 'FireGeometry': 'F'}
sel = collections.defaultdict(lambda: {'H': set(), 'M': set(), 'F': set()})
for l in open('gl.txt', encoding='latin1'):
    p = l.rstrip('\n').split('|')
    if p[0] == 'GS':
        sel[p[1]][LOD[p[2]]].add(p[3].lower())
parent = {}
for l in open('gp.txt', encoding='latin1'):
    p = l.rstrip('\n').split('|')
    if p[0] == 'GP' and p[3] == 'HP=<NULL-config>':
        parent[p[1]] = p[2]
addons = {}
for l in open('rootdata.txt', encoding='latin1'):
    p = l.rstrip('\n').split('|')
    if p[0] == 'RI':
        addons[p[1]] = json.loads(p[7]) if p[7] else []

# Wanted hitpoints come from the raw inputs, not anims_report.json, which gen_anims.py rewrites after reading
# extra_hitpoints.json: glass sources a model animates, named the way other configs name their hitpoint.
root_of = {}
for l in open('rootdata.txt', encoding='latin1'):
    p = l.rstrip('\n').split('|')
    if p[0] == 'RT':
        root_of[p[1]] = p[2]
learned = json.load(open('learned.json'))
def hit_name(src):
    for sig, n in learned.get(src, []):
        d = json.loads(sig)
        if d.get('source', '').lower() == 'hit' and d.get('hitpoint', '').lower().endswith('_hitpoint'):
            return d['hitpoint']
    return None
want = collections.defaultdict(set)
for l in open('animsrc.txt', encoding='latin1'):
    p = l.rstrip('\n').split('|')
    if len(p) >= 3 and re.match(r'(?i)glass_.*_source$', p[2].strip()) and p[0] in root_of:
        hp = hit_name(p[2].strip().lower())
        if hp:
            want[root_of[p[0]]].add(hp[:-len('_hitpoint')])

out, skipped = {}, collections.Counter()
for root, bases in want.items():
    s = sel.get(root)
    if root not in parent or not s:
        skipped['no data or has HitPoints'] += len(bases); continue
    # the fire-geometry component is <base>_hide in most models and <base> in some (A2 hospital)
    comp = {b: next((c for c in (b + '_hide', b) if c.lower() in s['F']), None) for b in bases}
    ok = sorted((b for b in bases if b.lower() in s['H'] and b.lower() + '_effects' in s['M'] and comp[b]),
                key=lambda b: [int(t) if t.isdigit() else t for t in re.split(r'(\d+)', b.lower())])
    skipped['selection missing'] += len(bases) - len(ok)
    if ok:
        out[root] = [(b, comp[b]) for b in ok]

addon = sys.argv[1]
names = sorted(out)
need = sorted({a for r in names for a in addons.get(r, [])})
L = ['#include "script_component.hpp"', '',
     '// Generated by dev_harness/loadall/anims/gen_glass.py: window hitpoints, as vanilla A3 buildings define them,',
     '// for buildings whose model carries glass selections but whose config has no HitPoints.',
     'class CfgPatches {', '    class ADDON {', '        name = COMPONENT_NAME;', '        units[] = {};', '        weapons[] = {};',
     '        requiredVersion = REQUIRED_VERSION;', '        requiredAddons[] = {', '            "uksf_common",']
L += [f'            "{a}",' for a in need]
L += ['        };', '    };', '};', '',
      '#define GLASS_EFFECT(BASE,TYPE) class BrokenGlass##TYPE { simulation = "particles"; type = QUOTE(BrokenGlass##TYPE##_0850_2250); position = QUOTE(BASE##_effects); intensity = 0.15; interval = 1; lifeTime = 0.05; }',
      '#define GLASS_HITPOINT(BASE,COMPONENT) class BASE##_hitpoint { armor = 0.001; material = -1; name = QUOTE(BASE); visual = QUOTE(BASE##_hide); passThrough = 0; radius = 0.4; convexComponent = QUOTE(COMPONENT); class DestructionEffects { ' +
      ' '.join(f'GLASS_EFFECT(BASE,{i}{t});' for t in 'NS' for i in range(1, 8)) + ' }; }', '',
      'class CfgVehicles {']
L += [f'    class {p};' for p in sorted({parent[r] for r in names} - set(names))]
done = set()
def emit(r):
    if r in done:
        return
    if parent[r] in out:
        emit(parent[r])
    done.add(r)
    L.append(f'    class {r}: {parent[r]} {{')
    L.append('        class HitPoints {')
    L.extend(f'            GLASS_HITPOINT({b},{c});' for b, c in out[r])
    L.extend(['        };', '    };'])
for r in names:
    emit(r)
L.append('};')
open(os.path.join(addon, 'config.cpp'), 'w', newline='\n').write('\n'.join(L) + '\n')
json.dump({r: [b + '_hitpoint' for b, _ in out[r]] for r in names}, open('extra_hitpoints.json', 'w'), indent=1)
print('buildings', len(out), 'hitpoints', sum(len(v) for v in out.values()), 'skipped', dict(skipped))
