PREP(assignWaypoints);
PREP(createAirForce);
PREP(createGroundForce);
PREP(handleDelete);
PREP(moduleAirSpawn);
PREP(moduleCounterBatteryUnits);
PREP(moduleGroundSpawn);
PREP(moduleUnitPools);
PREP(selectResponse);
