#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "uksf_vehicles",
            "uksf_weapons",
            "uksf_acr",
            "uksf_eug",
            "uksf_inegal"
        };
        author = QUOTE(UKSF);
        authors[] = { "Beswick.T" };
        url = URL;
        VERSION_CONFIG;
    };
};

// Generated by tools/vehicle_stabilisation. Stabilises every unstabilised land or sea vehicle
// turret that carries a real weapon (horns, smoke/flare launchers and safe placeholders do not
// count), except artillery and armour main guns. Land 3 axes, boats 4. Existing values are never lowered.
class CfgVehicles {
    #include "CfgVehicles.hpp"
};
