#include "script_component.hpp"

// Generated by dev_harness/loadall/anims/gen_glass.py: window hitpoints, as vanilla A3 buildings define them,
// for buildings whose model carries glass selections but whose config has no HitPoints.
class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "uksf_common",
            "CUP_A1_EditorObjects",
            "CUP_A2_EditorObjects",
            "CUP_Ind_Mlyn",
        };
    };
};

#define GLASS_EFFECT(BASE,TYPE) class BrokenGlass##TYPE { simulation = "particles"; type = QUOTE(BrokenGlass##TYPE##_0850_2250); position = QUOTE(BASE##_effects); intensity = 0.15; interval = 1; lifeTime = 0.05; }
#define GLASS_HITPOINT(BASE,COMPONENT) class BASE##_hitpoint { armor = 0.001; material = -1; name = QUOTE(BASE); visual = QUOTE(BASE##_hide); passThrough = 0; radius = 0.4; convexComponent = QUOTE(COMPONENT); class DestructionEffects { GLASS_EFFECT(BASE,1N); GLASS_EFFECT(BASE,2N); GLASS_EFFECT(BASE,3N); GLASS_EFFECT(BASE,4N); GLASS_EFFECT(BASE,5N); GLASS_EFFECT(BASE,6N); GLASS_EFFECT(BASE,7N); GLASS_EFFECT(BASE,1S); GLASS_EFFECT(BASE,2S); GLASS_EFFECT(BASE,3S); GLASS_EFFECT(BASE,4S); GLASS_EFFECT(BASE,5S); GLASS_EFFECT(BASE,6S); GLASS_EFFECT(BASE,7S); }; }

class CfgVehicles {
    class CUP_A1_Buildings;
    class CUP_A2_Civilian;
    class CUP_A2_Industry;
    class CUP_A2_Military;
    class CUP_A2_Walls;
    class House;
    class CUP_A1_Cihlovej_dum_mini: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
        };
    };
    class CUP_A1_SS_hangar: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
        };
    };
    class CUP_A1_SS_hangarD: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
        };
    };
    class CUP_A1_Sara_zluty_statek_in: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
        };
    };
    class CUP_A1_army_hut2_int: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
        };
    };
    class CUP_A1_budova3: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
        };
    };
    class CUP_A1_budova4_in: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
        };
    };
    class CUP_A1_hangar_2: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
        };
    };
    class CUP_A1_house_y: CUP_A1_Buildings {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
        };
    };
    class CUP_A2_barracks: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
        };
    };
    class CUP_A2_barracks_ep1: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
        };
    };
    class CUP_A2_barracks_i: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
        };
    };
    class CUP_A2_budova4_in: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
        };
    };
    class CUP_A2_controltower: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
            GLASS_HITPOINT(Glass_35,Glass_35_hide);
            GLASS_HITPOINT(Glass_36,Glass_36_hide);
            GLASS_HITPOINT(Glass_37,Glass_37_hide);
            GLASS_HITPOINT(Glass_38,Glass_38_hide);
            GLASS_HITPOINT(Glass_39,Glass_39_hide);
            GLASS_HITPOINT(Glass_40,Glass_40_hide);
            GLASS_HITPOINT(Glass_41,Glass_41_hide);
            GLASS_HITPOINT(Glass_42,Glass_42_hide);
            GLASS_HITPOINT(Glass_43,Glass_43_hide);
        };
    };
    class CUP_A2_controltower_ep1: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
            GLASS_HITPOINT(Glass_35,Glass_35_hide);
            GLASS_HITPOINT(Glass_36,Glass_36_hide);
            GLASS_HITPOINT(Glass_37,Glass_37_hide);
            GLASS_HITPOINT(Glass_38,Glass_38_hide);
            GLASS_HITPOINT(Glass_39,Glass_39_hide);
            GLASS_HITPOINT(Glass_40,Glass_40_hide);
            GLASS_HITPOINT(Glass_41,Glass_41_hide);
            GLASS_HITPOINT(Glass_42,Glass_42_hide);
            GLASS_HITPOINT(Glass_43,Glass_43_hide);
        };
    };
    class CUP_A2_fuelstation_build: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
        };
    };
    class CUP_A2_fuelstation_build_ep1: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
        };
    };
    class CUP_A2_fuelstation_build_pmc: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
        };
    };
    class CUP_A2_generalstore_01: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
            GLASS_HITPOINT(Glass_35,Glass_35_hide);
            GLASS_HITPOINT(Glass_36,Glass_36_hide);
            GLASS_HITPOINT(Glass_37,Glass_37_hide);
        };
    };
    class CUP_A2_generalstore_01a: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
            GLASS_HITPOINT(Glass_35,Glass_35_hide);
            GLASS_HITPOINT(Glass_36,Glass_36_hide);
            GLASS_HITPOINT(Glass_37,Glass_37_hide);
        };
    };
    class CUP_A2_guardhouse: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
        };
    };
    class CUP_A2_guardhouse_ep1: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
        };
    };
    class CUP_A2_hangar_2: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
        };
    };
    class CUP_A2_hangar_ep1: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
        };
    };
    class CUP_A2_hospital2: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1);
            GLASS_HITPOINT(Glass_2,Glass_2);
            GLASS_HITPOINT(Glass_3,Glass_3);
            GLASS_HITPOINT(Glass_4,Glass_4);
            GLASS_HITPOINT(Glass_5,Glass_5);
            GLASS_HITPOINT(Glass_6,Glass_6);
            GLASS_HITPOINT(Glass_7,Glass_7);
            GLASS_HITPOINT(Glass_8,Glass_8);
            GLASS_HITPOINT(Glass_9,Glass_9);
            GLASS_HITPOINT(Glass_10,Glass_10);
            GLASS_HITPOINT(Glass_11,Glass_11);
            GLASS_HITPOINT(Glass_12,Glass_12);
            GLASS_HITPOINT(Glass_13,Glass_13);
            GLASS_HITPOINT(Glass_14,Glass_14);
            GLASS_HITPOINT(Glass_15,Glass_15);
            GLASS_HITPOINT(Glass_16,Glass_16);
            GLASS_HITPOINT(Glass_17,Glass_17);
            GLASS_HITPOINT(Glass_18,Glass_18);
            GLASS_HITPOINT(Glass_19,Glass_19);
            GLASS_HITPOINT(Glass_20,Glass_20);
            GLASS_HITPOINT(Glass_21,Glass_21);
            GLASS_HITPOINT(Glass_22,Glass_22);
            GLASS_HITPOINT(Glass_23,Glass_23);
            GLASS_HITPOINT(Glass_24,Glass_24);
            GLASS_HITPOINT(Glass_25,Glass_25);
            GLASS_HITPOINT(Glass_26,Glass_26);
            GLASS_HITPOINT(Glass_27,Glass_27);
            GLASS_HITPOINT(Glass_28,Glass_28);
            GLASS_HITPOINT(Glass_29,Glass_29);
            GLASS_HITPOINT(Glass_30,Glass_30);
            GLASS_HITPOINT(Glass_31,Glass_31);
            GLASS_HITPOINT(Glass_32,Glass_32);
            GLASS_HITPOINT(Glass_33,Glass_33);
            GLASS_HITPOINT(Glass_34,Glass_34);
            GLASS_HITPOINT(Glass_35,Glass_35);
            GLASS_HITPOINT(Glass_36,Glass_36);
            GLASS_HITPOINT(Glass_37,Glass_37);
            GLASS_HITPOINT(Glass_38,Glass_38);
            GLASS_HITPOINT(Glass_39,Glass_39);
            GLASS_HITPOINT(Glass_40,Glass_40);
            GLASS_HITPOINT(Glass_41,Glass_41);
            GLASS_HITPOINT(Glass_42,Glass_42);
            GLASS_HITPOINT(Glass_43,Glass_43);
            GLASS_HITPOINT(Glass_44,Glass_44);
            GLASS_HITPOINT(Glass_45,Glass_45);
            GLASS_HITPOINT(Glass_46,Glass_46);
            GLASS_HITPOINT(Glass_47,Glass_47);
            GLASS_HITPOINT(Glass_48,Glass_48);
            GLASS_HITPOINT(Glass_49,Glass_49);
            GLASS_HITPOINT(Glass_50,Glass_50);
            GLASS_HITPOINT(Glass_51,Glass_51);
            GLASS_HITPOINT(Glass_52,Glass_52);
            GLASS_HITPOINT(Glass_53,Glass_53);
            GLASS_HITPOINT(Glass_54,Glass_54);
            GLASS_HITPOINT(Glass_56,Glass_56);
            GLASS_HITPOINT(Glass_57,Glass_57);
            GLASS_HITPOINT(Glass_58,Glass_58);
            GLASS_HITPOINT(Glass_59,Glass_59);
            GLASS_HITPOINT(glass_door_1,glass_door_1);
            GLASS_HITPOINT(glass_door_2,glass_door_2);
            GLASS_HITPOINT(glass_door_3_l,glass_door_3_l);
            GLASS_HITPOINT(glass_door_3_r,glass_door_3_r);
            GLASS_HITPOINT(glass_door_4,glass_door_4);
            GLASS_HITPOINT(glass_door_5,glass_door_5);
            GLASS_HITPOINT(glass_door_7,glass_door_7);
            GLASS_HITPOINT(glass_door_8,glass_door_8);
            GLASS_HITPOINT(glass_door_9,glass_door_9);
            GLASS_HITPOINT(glass_door_10,glass_door_10);
            GLASS_HITPOINT(glass_door_11,glass_door_11);
            GLASS_HITPOINT(glass_door_20,glass_door_20);
            GLASS_HITPOINT(glass_door_21,glass_door_21);
            GLASS_HITPOINT(glass_door_22,glass_door_22);
            GLASS_HITPOINT(glass_door_29,glass_door_29);
            GLASS_HITPOINT(glass_door_30,glass_door_30);
            GLASS_HITPOINT(glass_door_31,glass_door_31);
        };
    };
    class CUP_A2_house: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
        };
    };
    class CUP_A2_house_c_10_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
        };
    };
    class CUP_A2_house_c_11_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
        };
    };
    class CUP_A2_house_c_12_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
        };
    };
    class CUP_A2_house_c_1_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
        };
    };
    class CUP_A2_house_c_1_v2_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
        };
    };
    class CUP_A2_house_c_2_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
        };
    };
    class CUP_A2_house_c_3_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
            GLASS_HITPOINT(Glass_35,Glass_35_hide);
            GLASS_HITPOINT(Glass_36,Glass_36_hide);
            GLASS_HITPOINT(Glass_37,Glass_37_hide);
            GLASS_HITPOINT(Glass_38,Glass_38_hide);
            GLASS_HITPOINT(Glass_39,Glass_39_hide);
            GLASS_HITPOINT(Glass_40,Glass_40_hide);
            GLASS_HITPOINT(Glass_41,Glass_41_hide);
            GLASS_HITPOINT(Glass_42,Glass_42_hide);
        };
    };
    class CUP_A2_house_c_4_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
        };
    };
    class CUP_A2_house_c_5_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
        };
    };
    class CUP_A2_house_c_5_v1_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
        };
    };
    class CUP_A2_house_c_5_v2_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
        };
    };
    class CUP_A2_house_c_5_v3_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
        };
    };
    class CUP_A2_house_c_9_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
        };
    };
    class CUP_A2_house_ep1: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
        };
    };
    class CUP_A2_house_k_1_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
        };
    };
    class CUP_A2_house_k_3_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
        };
    };
    class CUP_A2_house_k_5_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
        };
    };
    class CUP_A2_house_k_6_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
        };
    };
    class CUP_A2_house_k_7_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
        };
    };
    class CUP_A2_house_k_8_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
        };
    };
    class CUP_A2_houseb_tenement: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
        };
    };
    class CUP_A2_housev2_02_interier: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
        };
    };
    class CUP_A2_housev2_04_interier: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
        };
    };
    class CUP_A2_housev_1i4: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
        };
    };
    class CUP_A2_mlyn_02: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
        };
    };
    class CUP_A2_mlyn_03: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
        };
    };
    class CUP_A2_mosque_big_addon_ep1: CUP_A2_Walls {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
        };
    };
    class CUP_A2_mosque_big_hq_ep1: CUP_A2_Walls {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
        };
    };
    class CUP_A2_office01: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
            GLASS_HITPOINT(Glass_35,Glass_35_hide);
            GLASS_HITPOINT(Glass_37,Glass_37_hide);
            GLASS_HITPOINT(Glass_39,Glass_39_hide);
            GLASS_HITPOINT(Glass_41,Glass_41_hide);
        };
    };
    class CUP_A2_office02: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
        };
    };
    class CUP_A2_pec_02: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1);
            GLASS_HITPOINT(Glass_2,Glass_2);
            GLASS_HITPOINT(Glass_3,Glass_3);
            GLASS_HITPOINT(Glass_4,Glass_4);
            GLASS_HITPOINT(Glass_5,Glass_5);
            GLASS_HITPOINT(Glass_6,Glass_6);
            GLASS_HITPOINT(Glass_7,Glass_7);
            GLASS_HITPOINT(Glass_8,Glass_8);
            GLASS_HITPOINT(Glass_9,Glass_9);
            GLASS_HITPOINT(Glass_10,Glass_10);
            GLASS_HITPOINT(Glass_11,Glass_11);
            GLASS_HITPOINT(Glass_12,Glass_12);
            GLASS_HITPOINT(Glass_13,Glass_13);
            GLASS_HITPOINT(Glass_14,Glass_14);
            GLASS_HITPOINT(Glass_15,Glass_15);
            GLASS_HITPOINT(Glass_16,Glass_16);
            GLASS_HITPOINT(Glass_17,Glass_17);
            GLASS_HITPOINT(Glass_18,Glass_18);
            GLASS_HITPOINT(Glass_19,Glass_19);
            GLASS_HITPOINT(Glass_20,Glass_20);
            GLASS_HITPOINT(Glass_21,Glass_21);
            GLASS_HITPOINT(Glass_22,Glass_22);
            GLASS_HITPOINT(Glass_23,Glass_23);
            GLASS_HITPOINT(Glass_24,Glass_24);
            GLASS_HITPOINT(Glass_25,Glass_25);
            GLASS_HITPOINT(Glass_26,Glass_26);
            GLASS_HITPOINT(Glass_27,Glass_27);
            GLASS_HITPOINT(Glass_28,Glass_28);
            GLASS_HITPOINT(Glass_29,Glass_29);
            GLASS_HITPOINT(Glass_30,Glass_30);
            GLASS_HITPOINT(Glass_31,Glass_31);
            GLASS_HITPOINT(Glass_32,Glass_32);
            GLASS_HITPOINT(Glass_33,Glass_33);
            GLASS_HITPOINT(Glass_34,Glass_34);
            GLASS_HITPOINT(Glass_35,Glass_35);
            GLASS_HITPOINT(Glass_36,Glass_36);
            GLASS_HITPOINT(Glass_37,Glass_37);
            GLASS_HITPOINT(Glass_38,Glass_38);
            GLASS_HITPOINT(Glass_39,Glass_39);
            GLASS_HITPOINT(Glass_40,Glass_40);
            GLASS_HITPOINT(Glass_41,Glass_41);
            GLASS_HITPOINT(Glass_42,Glass_42);
            GLASS_HITPOINT(Glass_43,Glass_43);
            GLASS_HITPOINT(Glass_44,Glass_44);
        };
    };
    class CUP_A2_pub_01: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
        };
    };
    class CUP_A2_shed_ind02: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
        };
    };
    class CUP_A2_ss_hangar: CUP_A2_Military {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
        };
    };
    class CUP_A2_stationhouse: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
            GLASS_HITPOINT(Glass_35,Glass_35_hide);
            GLASS_HITPOINT(Glass_36,Glass_36_hide);
            GLASS_HITPOINT(Glass_37,Glass_37_hide);
            GLASS_HITPOINT(Glass_38,Glass_38_hide);
            GLASS_HITPOINT(Glass_39,Glass_39_hide);
            GLASS_HITPOINT(Glass_40,Glass_40_hide);
            GLASS_HITPOINT(Glass_41,Glass_41_hide);
            GLASS_HITPOINT(Glass_42,Glass_42_hide);
            GLASS_HITPOINT(Glass_43,Glass_43_hide);
            GLASS_HITPOINT(Glass_44,Glass_44_hide);
            GLASS_HITPOINT(Glass_45,Glass_45_hide);
            GLASS_HITPOINT(Glass_46,Glass_46_hide);
            GLASS_HITPOINT(Glass_47,Glass_47_hide);
            GLASS_HITPOINT(Glass_48,Glass_48_hide);
            GLASS_HITPOINT(Glass_49,Glass_49_hide);
            GLASS_HITPOINT(Glass_50,Glass_50_hide);
            GLASS_HITPOINT(Glass_51,Glass_51_hide);
            GLASS_HITPOINT(Glass_52,Glass_52_hide);
        };
    };
    class CUP_A2_villa_ep1: CUP_A2_Civilian {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
            GLASS_HITPOINT(Glass_7,Glass_7_hide);
            GLASS_HITPOINT(Glass_8,Glass_8_hide);
            GLASS_HITPOINT(Glass_9,Glass_9_hide);
            GLASS_HITPOINT(Glass_10,Glass_10_hide);
            GLASS_HITPOINT(Glass_11,Glass_11_hide);
            GLASS_HITPOINT(Glass_12,Glass_12_hide);
            GLASS_HITPOINT(Glass_13,Glass_13_hide);
            GLASS_HITPOINT(Glass_14,Glass_14_hide);
            GLASS_HITPOINT(Glass_15,Glass_15_hide);
            GLASS_HITPOINT(Glass_16,Glass_16_hide);
            GLASS_HITPOINT(Glass_17,Glass_17_hide);
            GLASS_HITPOINT(Glass_18,Glass_18_hide);
            GLASS_HITPOINT(Glass_19,Glass_19_hide);
            GLASS_HITPOINT(Glass_20,Glass_20_hide);
            GLASS_HITPOINT(Glass_21,Glass_21_hide);
            GLASS_HITPOINT(Glass_22,Glass_22_hide);
            GLASS_HITPOINT(Glass_23,Glass_23_hide);
            GLASS_HITPOINT(Glass_24,Glass_24_hide);
            GLASS_HITPOINT(Glass_25,Glass_25_hide);
            GLASS_HITPOINT(Glass_26,Glass_26_hide);
            GLASS_HITPOINT(Glass_27,Glass_27_hide);
            GLASS_HITPOINT(Glass_28,Glass_28_hide);
            GLASS_HITPOINT(Glass_29,Glass_29_hide);
            GLASS_HITPOINT(Glass_30,Glass_30_hide);
            GLASS_HITPOINT(Glass_31,Glass_31_hide);
            GLASS_HITPOINT(Glass_32,Glass_32_hide);
            GLASS_HITPOINT(Glass_33,Glass_33_hide);
            GLASS_HITPOINT(Glass_34,Glass_34_hide);
            GLASS_HITPOINT(Glass_35,Glass_35_hide);
            GLASS_HITPOINT(Glass_36,Glass_36_hide);
            GLASS_HITPOINT(Glass_37,Glass_37_hide);
            GLASS_HITPOINT(Glass_38,Glass_38_hide);
            GLASS_HITPOINT(Glass_39,Glass_39_hide);
            GLASS_HITPOINT(Glass_40,Glass_40_hide);
            GLASS_HITPOINT(Glass_41,Glass_41_hide);
            GLASS_HITPOINT(Glass_42,Glass_42_hide);
            GLASS_HITPOINT(Glass_43,Glass_43_hide);
            GLASS_HITPOINT(Glass_44,Glass_44_hide);
            GLASS_HITPOINT(Glass_45,Glass_45_hide);
            GLASS_HITPOINT(Glass_46,Glass_46_hide);
            GLASS_HITPOINT(Glass_47,Glass_47_hide);
            GLASS_HITPOINT(Glass_48,Glass_48_hide);
            GLASS_HITPOINT(Glass_49,Glass_49_hide);
            GLASS_HITPOINT(Glass_50,Glass_50_hide);
            GLASS_HITPOINT(Glass_51,Glass_51_hide);
            GLASS_HITPOINT(Glass_52,Glass_52_hide);
            GLASS_HITPOINT(Glass_53,Glass_53_hide);
            GLASS_HITPOINT(Glass_54,Glass_54_hide);
            GLASS_HITPOINT(Glass_55,Glass_55_hide);
            GLASS_HITPOINT(Glass_56,Glass_56_hide);
            GLASS_HITPOINT(Glass_57,Glass_57_hide);
            GLASS_HITPOINT(Glass_58,Glass_58_hide);
            GLASS_HITPOINT(Glass_59,Glass_59_hide);
            GLASS_HITPOINT(Glass_60,Glass_60_hide);
            GLASS_HITPOINT(Glass_61,Glass_61_hide);
            GLASS_HITPOINT(Glass_62,Glass_62_hide);
            GLASS_HITPOINT(Glass_63,Glass_63_hide);
            GLASS_HITPOINT(Glass_64,Glass_64_hide);
            GLASS_HITPOINT(Glass_65,Glass_65_hide);
            GLASS_HITPOINT(Glass_66,Glass_66_hide);
            GLASS_HITPOINT(Glass_67,Glass_67_hide);
            GLASS_HITPOINT(Glass_68,Glass_68_hide);
            GLASS_HITPOINT(Glass_69,Glass_69_hide);
        };
    };
    class CUP_A2_workshop01_01: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
        };
    };
    class CUP_A2_workshop01_02: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
        };
    };
    class CUP_A2_workshop01_03: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
        };
    };
    class CUP_A2_workshop01_04: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
        };
    };
    class CUP_A2_workshop01_l: CUP_A2_Industry {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
            GLASS_HITPOINT(Glass_4,Glass_4_hide);
            GLASS_HITPOINT(Glass_5,Glass_5_hide);
            GLASS_HITPOINT(Glass_6,Glass_6_hide);
        };
    };
    class Land_Ind_Mlyn_03: House {
        class HitPoints {
            GLASS_HITPOINT(Glass_1,Glass_1_hide);
            GLASS_HITPOINT(Glass_2,Glass_2_hide);
            GLASS_HITPOINT(Glass_3,Glass_3_hide);
        };
    };
};
