PREP(initCurators);
PREP(disconnect);
PREP(addAction);
PREP(respawn);
PREP(getChildren);
PREP(getName);
PREP(actionStatement);
PREP(setAllowUnconcious);

PREP(moduleAddAllObjects);
PREP(moduleExplosionSmall);
PREP(moduleExplosionLarge);
PREP(moduleFullHeal);
PREP(moduleSetEngineer);
PREP(moduleTeleportZeus);
PREP(moduleToggleAllowUnconcious);
PREP(moduleToggleZeusVisibility);
PREP(moduleLoadoutCopy);
PREP(moduleLoadoutPaste);
