name: Arma

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v6
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT check
      run: hemtt check
    - name: Check for BOM
      uses: arma-actions/bom-check@master
      with:
        path: 'addons'

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v6
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT build
      run: hemtt build
